## **1. Import Libraries**

In [1]:
import pandas as pd

## **2. Collecting the DataSet**
For this project, we need a bunch of urls of type legitimate (0) and phishing (1).

## **2.1 Phishing URLs:**

In [ ]:
#loading the phishing URLs data to dataframe
data0 = pd.read_csv("/content/verified_online.csv")
data0.head()

,phish_id,url,phish_detail_url,submission_time,verified,verification_time,online,target
0,9311064,http://allegrolokalnie.pl-inne-24872.sbs,http://www.phishtank.com/phish_detail.php?phis...,2026-01-13T15:55:46+00:00,yes,2026-01-13T16:03:05+00:00,yes,Allegro
1,9311062,https://u58318934.ct.eu.sendgrid.net/ls/click?...,http://www.phishtank.com/phish_detail.php?phis...,2026-01-13T15:54:45+00:00,yes,2026-01-13T16:03:05+00:00,yes,Other
2,9311059,https://klelnanzeigen-deutch.obtain567.today/s...,http://www.phishtank.com/phish_detail.php?phis...,2026-01-13T15:53:42+00:00,yes,2026-01-13T16:03:06+00:00,yes,Other
3,9311058,https://klelnanzeigen-deutch.obtain567.today/r...,http://www.phishtank.com/phish_detail.php?phis...,2026-01-13T15:53:39+00:00,yes,2026-01-13T16:03:06+00:00,yes,Other
4,9311052,https://allegro-lokalnie.pl-59832.sbs/oferta/a...,http://www.phishtank.com/phish_detail.php?phis...,2026-01-13T15:40:41+00:00,yes,2026-01-13T15:42:00+00:00,yes,Allegro

In [ ]:
#Collecting 15,000 Phishing URLs randomly
phishurl = data0.sample(n = 15000, random_state = 12).copy()
phishurl = phishurl.reset_index(drop=True)
phishurl.head()

,phish_id,url,phish_detail_url,submission_time,verified,verification_time,online,target
0,9049376,https://docs.google.com/presentation/d/e/2PACX...,http://www.phishtank.com/phish_detail.php?phis...,2025-04-05T14:11:20+00:00,yes,2025-04-05T14:22:33+00:00,yes,Other
1,9302906,http://fun-purple-rabbit.31-22-4-140.cpanel.site/,http://www.phishtank.com/phish_detail.php?phis...,2026-01-02T08:42:01+00:00,yes,2026-01-02T08:52:09+00:00,yes,Other
2,9277256,https://linqapp.com/james_king8?r=link,http://www.phishtank.com/phish_detail.php?phis...,2025-11-26T10:18:48+00:00,yes,2025-11-26T10:21:58+00:00,yes,Other
3,9254690,https://e-igr.com/ABS/index.php?issue=163&limi...,http://www.phishtank.com/phish_detail.php?phis...,2025-10-30T16:30:15+00:00,yes,2025-10-30T16:41:52+00:00,yes,Other
4,9195392,https://us4.campaign-archive.com/?u=71c3658e7e...,http://www.phishtank.com/phish_detail.php?phis...,2025-08-27T08:57:59+00:00,yes,2025-08-27T09:12:26+00:00,yes,Other

In [ ]:
phishurl.shape

(15000, 8)

## **2.2 Legitimate URLs:**

In [ ]:
#Loading legitimate files
data1 = pd.read_csv("Safe.csv")
data1.columns = ['URLs']
data1.head()

                    URLs
0    https://youtube.com
1   https://facebook.com
2      https://baidu.com
3  https://wikipedia.org
4      https://yahoo.com

In [ ]:
#Collecting 15,000 Legitimate URLs randomly
legiurl = data1.sample(n = 10000, random_state = 12).copy()
legiurl = legiurl.reset_index(drop=True)
legiurl.head()

                   URLs
0    https://ebc.net.tw
1       https://jpn.org
2      https://cccd.edu
3        https://vrv.co
4  https://adshorte.com

In [ ]:
legiurl.shape

(10000, 1)

## **3. Feature Extraction**
The extracted features are categorized into



1.Address Bar based Features

2.Domain based Features

3.HTML & Javascript based Features

## **3.1. Address Bar Based Features:**
Many features can be extracted that can be consided as address bar base features. Out of them, below mentioned were considered for this project.


*   Domain of URL

*   IP Address in URL
*   "@" Symbol in URL


*   Length of URL

*   Depth of URL

*   Redirection "//" in URL

*   "http/https" in Domain name
*   Using URL Shortening Services “TinyURL”


*   Prefix or Suffix "-" in Domain

In [ ]:
# importing required packages for this section
from urllib.parse import urlparse,urlencode
import ipaddress
import re

## **3.1.1 Domain of the URL**

In [ ]:
# 1.Domain of the URL (Domain)
def getDomain(url):
    domain = urlparse(url).netloc
    if re.match(r"^www\.", domain):
        domain = re.sub(r"^www\.", "", domain)
    return domain

## **3.1.2. IP Address in the URL**

In [ ]:
# 2.Checks for IP address in URL (Have_IP)
def havingIP(url):
  try:
    ipaddress.ip_address(url)
    ip = 1
  except:
    ip = 0
  return ip

## **3.1.3. "@" Symbol in URL**

In [ ]:
# 3.Checks the presence of @ in URL (Have_At)
def haveAtSign(url):
  if "@" in url:
    at = 1
  else:
    at = 0
  return at

## **3.1.4. Length of URL**

In [ ]:
# 4.Finding the length of URL and categorizing (URL_Length)
def getLength(url):
  if len(url) < 54:
    length = 0
  else:
    length = 1
  return length

## **3.1.5. Depth of URL**

In [ ]:
# 5.Gives number of '/' in URL (URL_Depth)
def getDepth(url):
  s = urlparse(url).path.split('/')
  depth = 0
  for j in range(len(s)):
    if len(s[j]) != 0:
      depth = depth+1
  return depth

## **3.1.6. Redirection "//" in URL**

In [ ]:
# 6.Checking for redirection '//' in the url (Redirection)
def redirection(url):
  pos = url.rfind('//')
  if pos > 6:
    if pos > 7:
      return 1
    else:
      return 0
  else:
    return 0

## **3.1.7. "http/https" in Domain name**

In [ ]:
# 7.Existence of “HTTPS” Token in the Domain Part of the URL (https_Domain)
def httpDomain(url):
  domain = urlparse(url).netloc
  if 'https' in domain:
    return 1
  else:
    return 0

## **3.1.8. Using URL Shortening Services “TinyURL”**

In [ ]:
#listing shortening services
shortening_services = r"bit\.ly|goo\.gl|shorte\.st|go2l\.ink|x\.co|ow\.ly|t\.co|tinyurl|tr\.im|is\.gd|cli\.gs|" \
                      r"yfrog\.com|migre\.me|ff\.im|tiny\.cc|url4\.eu|twit\.ac|su\.pr|twurl\.nl|snipurl\.com|" \
                      r"short\.to|BudURL\.com|ping\.fm|post\.ly|Just\.as|bkite\.com|snipr\.com|fic\.kr|loopt\.us|" \
                      r"doiop\.com|short\.ie|kl\.am|wp\.me|rubyurl\.com|om\.ly|to\.ly|bit\.do|t\.co|lnkd\.in|db\.tt|" \
                      r"qr\.ae|adf\.ly|goo\.gl|bitly\.com|cur\.lv|tinyurl\.com|ow\.ly|bit\.ly|ity\.im|q\.gs|is\.gd|" \
                      r"po\.st|bc\.vc|twitthis\.com|u\.to|j\.mp|buzurl\.com|cutt\.us|u\.bb|yourls\.org|x\.co|" \
                      r"prettylinkpro\.com|scrnch\.me|filoops\.info|vzturl\.com|qr\.net|1url\.com|tweez\.me|v\.gd|" \
                      r"tr\.im|link\.zip\.net"

In [ ]:
# 8. Checking for Shortening Services in URL (Tiny_URL)
def tinyURL(url):
    match=re.search(shortening_services,url)
    if match:
        return 1
    else:
        return 0

## **3.1.9. Prefix or Suffix "-" in Domain**

In [ ]:
# 9.Checking for Prefix or Suffix Separated by (-) in the Domain (Prefix/Suffix)
def prefixSuffix(url):
    if '-' in urlparse(url).netloc:
        return 1            # phishing
    else:
        return 0            # legitimate

## **3.2. Domain Based Features:**
Many features can be extracted that come under this category. Out of them, below mentioned were considered for this project.
*   DNS Record

*   Website Traffic
*   Age of Domain


*   End Period of Domain

In [ ]:
!pip install python-whois

Collecting python-whois
  Downloading python_whois-0.9.6-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from python-whois) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->python-whois) (1.17.0)
Downloading python_whois-0.9.6-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.0/117.0 kB 5.3 MB/s eta 0:00:00
Installing collected packages: python-whois
Successfully installed python-whois-0.9.6

In [ ]:
# importing required packages for this section
import re
from bs4 import BeautifulSoup
import whois
import urllib
import urllib.request
from datetime import datetime

## **3.2.1. DNS Record**
For phishing websites, either the claimed identity is not recognized by the WHOIS database or no records founded for the hostname. If the DNS record is empty or not found then, the value assigned to this feature is 1 (phishing) or else 0 (legitimate).

In [ ]:
# 11.DNS Record availability (DNS_Record)
# obtained in the featureExtraction function itself

## **3.2.2. Web Traffic**

In [ ]:
# 12.Web traffic (Web_Traffic)
def web_traffic(url):
    try:
        # SimilarWeb and other APIs often block scripts.
        # We add a User-Agent header to look like a real browser.
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
        # Encode the URL
        url_encoded = urllib.parse.quote(url)
        # Note: The URL you used in the traceback might be outdated or require an API key.
        # If this API returns 404, we catch it here.
        rank_url = "https://api.similarweb.com/batch/v4/request-report" + url_encoded

        response = requests.get(rank_url, headers=headers, timeout=5)
        if response.status_code != 200:
            return 1 # Default value if the site isn't ranked or API fails

        # Parse logic here based on SimilarWeb's actual XML/JSON response
        # (Assuming your original .find("REACH") logic worked)
        return 0
    except:
        return 1 # If any network error occurs, treat as "no traffic/unknown"

## **3.2.3. Age of Domain**

In [ ]:
# 13.Survival time of domain: The difference between termination time and creation time (Domain_Age)
def domainAge(domain_name):
  creation_date = domain_name.creation_date
  expiration_date = domain_name.expiration_date
  if (isinstance(creation_date,str) or isinstance(expiration_date,str)):
    try:
      creation_date = datetime.strptime(creation_date,'%Y-%m-%d')
      expiration_date = datetime.strptime(expiration_date,"%Y-%m-%d")
    except:
      return 1
  if ((expiration_date is None) or (creation_date is None)):
      return 1
  elif ((type(expiration_date) is list) or (type(creation_date) is list)):
      return 1
  else:
    ageofdomain = abs((expiration_date - creation_date).days)
    if ((ageofdomain/30) < 6):
      age = 1
    else:
      age = 0
  return age

## **3.2.4. End Period of Domain**

In [ ]:
# 14.End time of domain: The difference between termination time and current time (Domain_End)
from datetime import datetime

def domainEnd(domain_name):
    # Initialize the variable to None at the very start
    expiration_date = None

    try:
        # Perform the whois lookup
        w = whois.whois(domain_name)
        expiration_date = w.expiration_date

        # WHOIS sometimes returns a list of dates; take the first one
        if isinstance(expiration_date, list):
            expiration_date = expiration_date[0]

    except Exception:
        # If whois fails, expiration_date stays None
        pass

    # Now this check will work because the variable exists
    if not expiration_date:
        return 1
    else:
        today = datetime.now()

        # Clean the timezone (Fix for your previous TypeError)
        if expiration_date.tzinfo is not None:
            expiration_date = expiration_date.replace(tzinfo=None)

        try:
            end = abs((expiration_date - today).days)
            # If remaining time is less than 6 months (approx 180 days)
            return 1 if (end / 30) < 6 else 0
        except:
            return 1

## **3.3. HTML and JavaScript based Features**
Many features can be extracted that come under this category. Out of them, below mentioned were considered for this project.



*   IFrame Redirection

*   Status Bar Customization

*   Disabling Right Click
*   Website Forwarding

Each of these features are explained and the coded below:

In [ ]:
# importing required packages for this section
import requests

## **3.3.1. IFrame Redirection**

In [ ]:
# 15. IFrame Redirection (iFrame)
def iframe(html_content):
  if html_content == "":
    return 1
  else:
    if re.findall(r"[<iframe>|<frameBorder>]", html_content):
      return 0
    else:
      return 1

## **3.3.2. Status Bar Customization**

In [ ]:
# 16.Checks the effect of mouse over on status bar (Mouse_Over)
def mouseOver(html_content):
    if html_content == "" :
      return 1
    else:
      if re.findall("<script>.+onmouseover.+</script>", html_content):
        return 1
      else:
        return 0

## **3.3.3. Disabling Right Click**

In [ ]:
# 17.Checks the status of the right click attribute (Right_Click)
def rightClick(html_content):
  if html_content == "":
    return 1
  else:
# Notice we just use html_content here, NOT html_content.text
    if re.findall(r"event.button ?== ?2", html_content):
      return 0
    else:
      return 1

## **3.3.4. Website Forwarding**

In [ ]:
# 18.Checks the number of forwardings (Web_Forwards)
def forwarding(response):
  if response == "" or response is None:
    return 1
  else:
    if len(response.history) <= 2:
      return 0
    else:
      return 1

## **4. Computing URL Features**
Create a list and a function that calls the other functions and stores all the features of the URL in the list. We will extract the features of each URL and append to this list.

In [ ]:
#Function to extract features
def featureExtraction(url, label, response):
    features = []

    # 1. Handle HTML content safely
    # If the loop failed to get a response, we use an empty string
    if response is not None:
        html_content = response.text
    else:
        html_content = ""

    # 2. Address Bar Based Features
    features.append(getDomain(url))
    features.append(havingIP(url))
    features.append(haveAtSign(url))
    features.append(getLength(url))
    features.append(getDepth(url))
    features.append(redirection(url))
    features.append(httpDomain(url))
    features.append(tinyURL(url))
    features.append(prefixSuffix(url))

    # 3. Domain Based Features (DNS/WHOIS)
    dns = 0
    domain_name = None
    try:
        domain_name = whois.whois(urlparse(url).netloc)
    except:
        dns = 1

    features.append(dns)
    features.append(web_traffic(url))
    features.append(1 if dns == 1 else domainAge(domain_name))
    features.append(1 if dns == 1 else domainEnd(domain_name))

    # 4. HTML & Javascript Features
    # These functions must take the STRING 'html_content'
    features.append(iframe(html_content))
    features.append(mouseOver(html_content))
    features.append(rightClick(html_content))
    features.append(forwarding(response))

    features.append(label)
    return features

## **4.1. Legitimate URLs:**

In [ ]:
legiurl.shape

(10000, 1)

In [ ]:

#Extracting the feautres & storing them in a list
import requests
import csv
import os

legi_features = []
label = 0
start_index = 4500 # If you crash at 3500, change this to 3500 and run again!
total_urls = 6100
checkpoint_interval = 100

# Use a session to manage network resources efficiently
session = requests.Session()

# Create or prepare the CSV file for saving progress
csv_filename = "legi_features_backup(4).csv"

for i in range(start_index, total_urls):
    url = legiurl['URLs'][i]

    # Wrap the ENTIRE process for this URL in a try block
    try:
        response = session.get(url, timeout=5)
        features = featureExtraction(url, label, response)
    except Exception as e:
        # If ANYTHING goes wrong (network error, extraction error), catch it
        print(f"Error processing URL {i} ({url}): {e}")
        # Assuming your function can handle 'None' for a completely failed attempt
        try:
             features = featureExtraction(url, label, None)
        except Exception:
             # If even the fallback fails, append empty/null data so rows align
             features = {"url": url, "error": str(e)}

    legi_features.append(features)

    # Checkpoint: Save to CSV and clear memory every 100 URLs
    if (i + 1) % checkpoint_interval == 0 or (i + 1) == total_urls:
        print(f"Processed {i + 1} URLs. Saving checkpoint...")

        # Check if file exists so we only write headers once
        file_exists = os.path.isfile(csv_filename)

        with open(csv_filename, 'a', newline='', encoding='utf-8') as f:
            # Assuming 'features' is a dictionary. If it's a list, use csv.writer instead.
            if isinstance(features, dict):
                writer = csv.DictWriter(f, fieldnames=features.keys())
                if not file_exists:
                    writer.writeheader()
                writer.writerows(legi_features)
            else:
                writer = csv.writer(f)
                writer.writerows(legi_features)

        # Clear the list to free up RAM!
        legi_features = []

print("Extraction complete!")

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Error processing URL 4502 (https://miit.gov.cn): HTTPSConnectionPool(host='miit.gov.cn', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b464f19070>: Failed to resolve 'miit.gov.cn' ([Errno -5] No address associated with hostname)"))
Error processing URL 4503 (https://nsovetnik.ru): HTTPSConnectionPool(host='nsovetnik.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1010)')))
Error processing URL 4504 (https://72byte.com): HTTPSConnectionPool(host='72byte.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for '72byte.com'. (_ssl.c:1010)")))
Error processing URL 4507 (https://clickredirection.com): HTTPSConnectionPool(host='clickredirection.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da8aba0>: Failed to resolve 'clickredirection.com' ([Errno -2] Name or service not known)"))
Error processing URL 4513 (https://nakehub.com): HTTPSConnectionPool(host='nakehub.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b464f75be0>: Failed to resolve 'nakehub.com' ([Errno -2] Name or service not known)"))
Error processing URL 4514 (https://nyugator.info): HTTPSConnectionPool(host='nyugator.info', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da8aae0>: Failed to resolve 'nyugator.info' ([Errno -2] Name or service not known)"))
Error processing URL 4515 (https://nend.net): HTTPSConnectionPool(host='nend.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da89010>: Failed to resolve 'nend.net' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4523 (https://konkur.in): HTTPSConnectionPool(host='konkur.in', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43da89ca0>, 'Connection to konkur.in timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4531 (https://animesorion.org): HTTPSConnectionPool(host='animesorion.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d9499d0>: Failed to resolve 'animesorion.org' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4535 (https://1fardadownload.net): HTTPSConnectionPool(host='1fardadownload.net', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d94a9f0>, 'Connection to 1fardadownload.net timed out. (connect timeout=5)'))
Error processing URL 4546 (https://otakomu.jp): HTTPSConnectionPool(host='otakomu.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1010)')))
Error processing URL 4563 (https://rcfans.com): HTTPSConnectionPool(host='rcfans.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d94a7e0>, 'Connection to rcfans.com timed out. (connect timeout=5)'))
Error processing URL 4568 (https://stoa.pw): HTTPSConnectionPool(host='stoa.pw', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d94a900>: Failed to resolve 'stoa.pw' ([Errno -2] Name or service not known)"))
Error processing URL 4574 (https://dti.ne.jp): HTTPSConnectionPool(host='dti.ne.jp', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d938200>: Failed to resolve 'dti.ne.jp' ([Errno -5] No address associated with hostname)"))
Error processing URL 4575 (https://thaidress-wholesale.com): HTTPSConnectionPool(host='thaidress-wholesale.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d81f530>: Failed to resolve 'thaidress-wholesale.com' ([Errno -2] Name or service not known)"))
Error processing URL 4577 (https://moh.gov.sa): HTTPSConnectionPool(host='moh.gov.sa', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b43cce4350>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
Error processing URL 4580 (https://cne.gob.ve): HTTPSConnectionPool(host='cne.gob.ve', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cce7920>: Failed to resolve 'cne.gob.ve' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4599 (https://evand.com): HTTPSConnectionPool(host='evand.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d9385f0>, 'Connection to evand.com timed out. (connect timeout=5)'))
Processed 4600 URLs. Saving checkpoint...
Error processing URL 4601 (https://weqpkntrxqzh.com): HTTPSConnectionPool(host='weqpkntrxqzh.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b464f482f0>: Failed to resolve 'weqpkntrxqzh.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4604 (https://applycareer.co.in): HTTPSConnectionPool(host='applycareer.co.in', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)')))
Error processing URL 4612 (https://zuipin.cn): HTTPSConnectionPool(host='zuipin.cn', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d917f80>, 'Connection to zuipin.cn timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Error processing URL 4618 (https://shikimori.org): HTTPSConnectionPool(host='shikimori.org', port=443): Read timed out. (read timeout=5)
Error processing URL 4621 (https://kdmid.ru): HTTPSConnectionPool(host='kdmid.ru', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d948290>: Failed to resolve 'kdmid.ru' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4626 (https://leboutique.com): HTTPSConnectionPool(host='leboutique.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da895b0>: Failed to resolve 'leboutique.com' ([Errno -2] Name or service not known)"))
Error processing URL 4627 (https://oecd.org): HTTPSConnectionPool(host='oecd.org', port=443): Read timed out. (read timeout=5)
Error processing URL 4632 (https://euroset.ru): HTTPSConnectionPool(host='euroset.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'euroset.ru'. (_ssl.c:1010)")))
Error processing URL 4633 (https://rosewholesale.com): HTTPSConnectionPool(host='rosewholesale.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d81ff20>: Failed to resolve 'rosewholesale.com' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 4639 (https://metaffiliation.com): HTTPSConnectionPool(host='metaffiliation.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'metaffiliation.com'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4651 (https://republika.pl): HTTPSConnectionPool(host='republika.pl', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1010)')))
Error processing URL 4654 (https://amateurs-gone-wild.com): HTTPSConnectionPool(host='amateurs-gone-wild.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d949f70>, 'Connection to amateurs-gone-wild.com timed out. (connect timeout=5)'))
Error processing URL 4659 (https://skydaz.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 4662 (https://getspacecloud.org): HTTPSConnectionPool(host='getspacecloud.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d85fe90>: Failed to resolve 'getspacecloud.org' ([Errno -2] Name or service not known)"))
Error processing URL 4664 (https://ultratools.com): HTTPSConnectionPool(host='ultratools.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b44cb0ccb0>: Failed to establish a new connection: [Errno 111] Connection refused'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4668 (https://hdslb.com): HTTPSConnectionPool(host='hdslb.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da8bbf0>: Failed to resolve 'hdslb.com' ([Errno -5] No address associated with hostname)"))
Error processing URL 4671 (https://mtn.co.za): HTTPSConnectionPool(host='mtn.co.za', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)')))
Error processing URL 4673 (https://motorcycle-superstore.com): HTTPSConnectionPool(host='motorcycle-superstore.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43cc49dc0>, 'Connection to motorcycle-superstore.com timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4677 (https://07net01.com): HTTPSConnectionPool(host='07net01.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da8bbf0>: Failed to resolve '07net01.com' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4679 (https://redecanais.com): HTTPSConnectionPool(host='redecanais.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da8ad20>: Failed to resolve 'redecanais.com' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 4680 (https://dj6u.com): HTTPSConnectionPool(host='dj6u.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'dj6u.com'. (_ssl.c:1010)")))
Error processing URL 4685 (https://sld.cu): HTTPSConnectionPool(host='sld.cu', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d87ed80>: Failed to resolve 'sld.cu' ([Errno -5] No address associated with hostname)"))
Error processing URL 4686 (https://sb24.com): HTTPSConnectionPool(host='sb24.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d983860>, 'Connection to sb24.com timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4699 (https://shopfacil.com.br): HTTPSConnectionPool(host='shopfacil.com.br', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d983e60>, 'Connection to shopfacil.com.br timed out. (connect timeout=5)'))
Processed 4700 URLs. Saving checkpoint...
Error processing URL 4700 (https://huihui.cn): HTTPSConnectionPool(host='huihui.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b43d87ed50>: Failed to establish a new connection: [Errno 111] Connection refused'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Error processing URL 4709 (https://mycouchtuner.ag): HTTPSConnectionPool(host='mycouchtuner.ag', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d94b020>: Failed to resolve 'mycouchtuner.ag' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4711 (https://gogoanime.io): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4713 (https://oabt03.com): HTTPSConnectionPool(host='oabt03.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b44cb0ccb0>: Failed to resolve 'oabt03.com' ([Errno -2] Name or service not known)"))
Error processing URL 4717 (https://statesman.com): HTTPSConnectionPool(host='statesman.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d95a810>, 'Connection to statesman.com timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4718 (https://vslovetv.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 4719 (https://southfront.org): HTTPSConnectionPool(host='southfront.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce8cd70>: Failed to resolve 'southfront.org' ([Errno -2] Name or service not known)"))
Error processing URL 4720 (https://kemdikbud.go.id): HTTPSConnectionPool(host='kemdikbud.go.id', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da8bd10>: Failed to resolve 'kemdikbud.go.id' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 113] No route to host

Error processing URL 4723 (https://attendance.gov.in): HTTPSConnectionPool(host='attendance.gov.in', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43ce184a0>, 'Connection to attendance.gov.in timed out. (connect timeout=5)'))
Error processing URL 4726 (https://hdvidz.co): HTTPSConnectionPool(host='hdvidz.co', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cde87d0>: Failed to resolve 'hdvidz.co' ([Errno -2] Name or service not known)"))
Error processing URL 4728 (https://freemp3now.me): HTTPSConnectionPool(host='freemp3now.me', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b444213da0>: Failed to resolve 'freemp3now.me' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4729 (https://rooshvforum.com): HTTPSConnectionPool(host='rooshvforum.com', port=443): Read timed out. (read timeout=5)
Error processing URL 4738 (https://gibdd.ru): HTTPSConnectionPool(host='gibdd.ru', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43da89730>, 'Connection to gibdd.ru timed out. (connect timeout=5)'))
Error processing URL 4740 (https://2ch.net): HTTPSConnectionPool(host='2ch.net', port=443): Read timed out. (read timeout=5)
Error processing URL 4743 (https://daneshjooyar.com): HTTPSConnectionPool(host='daneshjooyar.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce5e2a0>: Failed to resolve 'daneshjooyar.com' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 4744 (https://instaliga.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 4745 (https://alalam.ir): HTTPSConnectionPool(host='alalam.ir', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1010)')))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4748 (https://avio.pw): HTTPSConnectionPool(host='avio.pw', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cae2930>: Failed to resolve 'avio.pw' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 4750 (https://panda-streaming.net): HTTPSConnectionPool(host='panda-streaming.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d94b020>: Failed to resolve 'panda-streaming.net' ([Errno -2] Name or service not known)"))
Error processing URL 4755 (https://evz.ro): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 4756 (https://electronics-tutorials.ws): HTTPSConnectionPool(host='www.electronics-tutorials.ws', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4761 (https://n152adserv.com): HTTPSConnectionPool(host='n152adserv.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d8a4410>: Failed to resolve 'n152adserv.com' ([Errno -2] Name or service not known)"))
Error processing URL 4768 (https://bet9ja.com): HTTPSConnectionPool(host='bet9ja.com', port=443): Read timed out. (read timeout=5)
Error processing URL 4770 (https://just.ro): HTTPSConnectionPool(host='just.ro', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43ce8ffb0>, 'Connection to just.ro timed out. (connect timeout=5)'))
Error processing URL 4771 (https://freeproxy.io): HTTPSConnectionPool(host='freeproxy.io', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4775 (https://cmle.ru): HTTPSConnectionPool(host='cmle.ru', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce8e5d0>: Failed to resolve 'cmle.ru' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 4778 (https://mitbbs.com): HTTPSConnectionPool(host='mitbbs.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d9815b0>, 'Connection to mitbbs.com timed out. (connect timeout=5)'))
Error processing URL 4780 (https://51banhui.com): HTTPSConnectionPool(host='51banhui.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b43d9809e0>: Failed to establish a new connection: [Errno 111] Connection refused'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4785 (https://aujourdhui.fr): HTTPSConnectionPool(host='aujourdhui.fr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43ce8dd30>, 'Connection to aujourdhui.fr timed out. (connect timeout=5)'))
Error processing URL 4788 (https://itasportpress.it): HTTPSConnectionPool(host='itasportpress.it', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d980800>: Failed to resolve 'itasportpress.it' ([Errno -5] No address associated with hostname)"))
Error processing URL 4791 (https://pinkdino.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 4792 (https://ponisha.ir): HTTPSConnectionPool(host='ponisha.ir', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d980140>, 'Connection to ponisha.ir timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 4796 (https://torrentor.co): HTTPSConnectionPool(host='torrentor.co', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d8a5ee0>: Failed to resolve 'torrentor.co' ([Errno -2] Name or service not known)"))
Error processing URL 4798 (https://popin.cc): HTTPSConnectionPool(host='popin.cc', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d8a57c0>: Failed to resolve 'popin.cc' ([Errno -5] No address associated with hostname)"))
Processed 4800 URLs. Saving checkpoint...
Error processing URL 4804 (https://weevah2.top): HTTPSConnectionPool(host='weevah2.top', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce8ef90>: Failed to resolve 'weevah2.top' ([Errno -2] Name or service not known)"))
Error processing URL 4805 (https://teniunet.com): HTTPSConnectionPool(host='teniunet.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d85d400>: Failed to resolve 'teniunet.com' ([Errno -2] Name or service not known)"))
Error processing URL 4808 (https://1dl.biz): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 4811 (https://erotube.org): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4816 (https://urle.co): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 4819 (https://totaljobs.com): HTTPSConnectionPool(host='totaljobs.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)')))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4820 (https://sportpeaks.com): HTTPSConnectionPool(host='sportpeaks.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b43d8a47a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error processing URL 4821 (https://disquscdn.com): HTTPSConnectionPool(host='disquscdn.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d85fcb0>: Failed to resolve 'disquscdn.com' ([Errno -5] No address associated with hostname)"))
Error processing URL 4823 (https://estrenos10.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 4825 (https://ppomppu.co.kr): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 4826 (https://pufnoktalari.net): HTTPSConnectionPool(host='pufnoktalari.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d94ae10>: Failed to resolve 'pufnoktalari.net' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 4830 (https://plusone8.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 4833 (https://a4l.co): HTTPSConnectionPool(host='a4l.co', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d847890>: Failed to resolve 'a4l.co' ([Errno -2] Name or service not known)"))
Error processing URL 4834 (https://dawnfun.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 4839 (https://realblog.pro): HTTPSConnectionPool(host='realblog.pro', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce109e0>: Failed to resolve 'realblog.pro' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 4842 (https://mhlearnsmart.com): HTTPSConnectionPool(host='mhlearnsmart.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d93a9c0>: Failed to resolve 'mhlearnsmart.com' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4852 (https://vipon.com): HTTPSConnectionPool(host='vipon.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d93ac30>, 'Connection to vipon.com timed out. (connect timeout=5)'))
Error processing URL 4857 (https://shemsfm.net): HTTPSConnectionPool(host='shemsfm.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d9392b0>: Failed to resolve 'shemsfm.net' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 4859 (https://uaemex.mx): HTTPSConnectionPool(host='uaemex.mx', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'uaemex.mx'. (_ssl.c:1010)")))
Error processing URL 4862 (https://seratnews.ir): HTTPSConnectionPool(host='seratnews.ir', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43cae27b0>, 'Connection to seratnews.ir timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 4865 (https://solidfiles.com): HTTPSConnectionPool(host='solidfiles.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce106e0>: Failed to resolve 'solidfiles.com' ([Errno -3] Temporary failure in name resolution)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4873 (https://mysites123.com): HTTPSConnectionPool(host='mysites123.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1010)')))
Error processing URL 4876 (https://btba.com.cn): HTTPSConnectionPool(host='btba.com.cn', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'btba.com.cn'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4886 (https://dataprev.gov.br): HTTPSConnectionPool(host='dataprev.gov.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1010)')))
Error processing URL 4887 (https://ubisoft.org): HTTPSConnectionPool(host='ubisoft.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce13b00>: Failed to resolve 'ubisoft.org' ([Errno -5] No address associated with hostname)"))
Error processing URL 4893 (https://l74fa.com): HTTPSConnectionPool(host='l74fa.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce8ff50>: Failed to resolve 'l74fa.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4898 (https://cartasi.it): HTTPSConnectionPool(host='cartasi.it', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce19d00>: Failed to resolve 'cartasi.it' ([Errno -5] No address associated with hostname)"))
Processed 4900 URLs. Saving checkpoint...
Error processing URL 4901 (https://animakai.info): HTTPSConnectionPool(host='animakai.info', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce190a0>: Failed to resolve 'animakai.info' ([Errno -2] Name or service not known)"))
Error processing URL 4903 (https://perspolisnews.com): HTTPSConnectionPool(host='perspolisnews.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b44476e570>: Failed to resolve 'perspolisnews.com' ([Errno -3] Temporary failure in name resolution)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4914 (https://adreactor.com): HTTPSConnectionPool(host='adreactor.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'adreactor.com'. (_ssl.c:1010)")))
Error processing URL 4915 (https://songfacts.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 4919 (https://gob.bo): HTTPSConnectionPool(host='gob.bo', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'gob.bo'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Error processing URL 4921 (https://iwanttodeliver.com): HTTPSConnectionPool(host='iwanttodeliver.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43da88560>, 'Connection to iwanttodeliver.com timed out. (connect timeout=5)'))
Error processing URL 4924 (https://instacoinprofits.com): HTTPSConnectionPool(host='instacoinprofits.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce8f6e0>: Failed to resolve 'instacoinprofits.com' ([Errno -2] Name or service not known)"))
Error processing URL 4925 (https://social-funding-project.info): HTTPSConnectionPool(host='social-funding-project.info', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cb0a690>: Failed to resolve 'social-funding-project.info' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Error processing URL 4935 (https://thecookedpea.com): HTTPSConnectionPool(host='thecookedpea.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cdea8d0>: Failed to resolve 'thecookedpea.com' ([Errno -2] Name or service not known)"))
Error processing URL 4937 (https://sumatoad.com): HTTPSConnectionPool(host='sumatoad.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1010)')))
Error processing URL 4939 (https://crowdflower.com): HTTPSConnectionPool(host='crowdflower.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce11940>: Failed to resolve 'crowdflower.com' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4944 (https://videodownloadconverter.com): HTTPSConnectionPool(host='videodownloadconverter.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1010)')))
Error processing URL 4949 (https://pubg.io): HTTPSConnectionPool(host='pubg.io', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da89e80>: Failed to resolve 'pubg.io' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4950 (https://xianzhidao.com): HTTPSConnectionPool(host='xianzhidao.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d9385f0>, 'Connection to xianzhidao.com timed out. (connect timeout=5)'))
Error processing URL 4951 (https://x-legend.co.jp): HTTPSConnectionPool(host='x-legend.co.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1010)')))
Error processing URL 4952 (https://localnewschannel7.online): HTTPSConnectionPool(host='localnewschannel7.online', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d939520>: Failed to resolve 'localnewschannel7.online' ([Errno -2] Name or service not known)"))
Error processing URL 4953 (https://fullhdfilmizlebe.net): HTTPSConnectionPool(host='fullhdfilmizlebe.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da8a1b0>: Failed to resolve 'fullhdfilmizlebe.net' ([Errno -2] Name or service not known)"))
Error processing URL 4964 (https://fpgameslinks.com): HTTPSConnectionPool(host='fpgameslinks.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da89880>: Failed to resolve 'fpgameslinks.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 4968 (https://anonimizing.com): HTTPSConnectionPool(host='anonimizing.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43da89c40>, 'Connection to anonimizing.com timed out. (connect timeout=5)'))
Error processing URL 4969 (https://jsyks.com): ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Error processing URL 4973 (https://mrooms3.net): HTTPSConnectionPool(host='mrooms3.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cce4320>: Failed to resolve 'mrooms3.net' ([Errno -5] No address associated with hostname)"))
Error processing URL 4977 (https://yes123.com.tw): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 4979 (https://mangareader.net): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 4981 (https://snapmyscreen.com): HTTPSConnectionPool(host='snapmyscreen.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cde8f20>: Failed to resolve 'snapmyscreen.com' ([Errno -5] No address associated with hostname)"))
Error processing URL 4983 (https://frtyg.com): HTTPSConnectionPool(host='frtyg.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cdeb530>: Failed to resolve 'frtyg.com' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 104] Connection reset by peer

Error processing URL 4985 (https://reyezr.com): HTTPSConnectionPool(host='reyezr.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da8bbc0>: Failed to resolve 'reyezr.com' ([Errno -2] Name or service not known)"))
Error processing URL 4986 (https://getthere.net): HTTPSConnectionPool(host='getthere.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d85e690>: Failed to resolve 'getthere.net' ([Errno -5] No address associated with hostname)"))
Error processing URL 4994 (https://mango02.com): HTTPSConnectionPool(host='mango02.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cde96d0>: Failed to resolve 'mango02.com' ([Errno -2] Name or service not known)"))
Error processing URL 4996 (https://ilxdh.com): HTTPSConnectionPool(host='ilxdh.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1010)')))
Error processing URL 4999 (https://softwarefixed.com): HTTPSConnectionPool(host='softwarefixed.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cb0a5a0>: Failed to resolve 'softwarefixed.com' ([Errno -2] Name or service not known)"))
Processed 5000 URLs. Saving checkpoint...
Error processing URL 5000 (https://egou.com): HTTPSConnectionPool(host='egou.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d8a7650>: Failed to resolve 'egou.com' ([Errno -5] No address associated with hostname)"))
Error processing URL 5001 (https://usenet-4all.info): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5003 (https://yaske.ro): HTTPSConnectionPool(host='yaske.ro', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43cb09820>, 'Connection to yaske.ro timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5012 (https://rightel.ir): HTTPSConnectionPool(host='rightel.ir', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b464f75d30>: Failed to resolve 'rightel.ir' ([Errno -3] Temporary failure in name resolution)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 5013 (https://dl-protecte.com): HTTPSConnectionPool(host='dl-protecte.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cae2060>: Failed to resolve 'dl-protecte.com' ([Errno -2] Name or service not known)"))
Error processing URL 5016 (https://o-xe.com): HTTPSConnectionPool(host='o-xe.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d93b110>, 'Connection to o-xe.com timed out. (connect timeout=5)'))
Error processing URL 5018 (https://extra.com.br): HTTPSConnectionPool(host='extra.com.br', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5032 (https://dramalink.net): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5035 (https://bornanews.ir): HTTPSConnectionPool(host='bornanews.ir', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cde89b0>: Failed to resolve 'bornanews.ir' ([Errno -3] Temporary failure in name resolution)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5040 (https://kh.edu.tw): HTTPSConnectionPool(host='kh.edu.tw', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d939cd0>: Failed to resolve 'kh.edu.tw' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5045 (https://rogers.com): HTTPSConnectionPool(host='rogers.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)')))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5047 (https://k12.ga.us): HTTPSConnectionPool(host='k12.ga.us', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cdea480>: Failed to resolve 'k12.ga.us' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Error processing URL 5050 (https://sockshare.net): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5054 (https://audiocastle2.info): HTTPSConnectionPool(host='audiocastle2.info', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d81d430>: Failed to resolve 'audiocastle2.info' ([Errno -2] Name or service not known)"))
Error processing URL 5057 (https://2p.com): HTTPSConnectionPool(host='2p.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1010)')))
Error processing URL 5061 (https://hentairules.net): HTTPSConnectionPool(host='hentairules.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce5f710>: Failed to resolve 'hentairules.net' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 5063 (https://gcxc168.com): HTTPSConnectionPool(host='gcxc168.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'gcxc168.com'. (_ssl.c:1010)")))
Error processing URL 5065 (https://chetor.com): HTTPSConnectionPool(host='chetor.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d8a5cd0>, 'Connection to chetor.com timed out. (connect timeout=5)'))
Error processing URL 5067 (https://livedoor.jp): HTTPSConnectionPool(host='livedoor.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'livedoor.jp'. (_ssl.c:1010)")))
Error processing URL 5070 (https://muji8.org): HTTPSConnectionPool(host='muji8.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d95bb30>: Failed to resolve 'muji8.org' ([Errno -2] Name or service not known)"))
Error processing URL 5073 (https://pes-patch.com): HTTPSConnectionPool(host='www.fc-sion-live.ch', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b43d9391c0>: Failed to establish a new connection: [Errno 111] Connection refused'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5077 (https://rcgroups.com): HTTPSConnectionPool(host='rcgroups.com', port=443): Read timed out. (read timeout=5)
Error processing URL 5078 (https://leagueoflegendsreplay.org): HTTPSConnectionPool(host='leagueoflegendsreplay.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce1a690>: Failed to resolve 'leagueoflegendsreplay.org' ([Errno -2] Name or service not known)"))
Error processing URL 5080 (https://360game.vn): HTTPSConnectionPool(host='360game.vn', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d87ee70>, 'Connection to 360game.vn timed out. (connect timeout=5)'))
Error processing URL 5082 (https://zhcw.com): HTTPSConnectionPool(host='zhcw.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1010)')))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5086 (https://live-rutor.org): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5090 (https://businessplancity.com): HTTPSConnectionPool(host='businessplancity.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da8b260>: Failed to resolve 'businessplancity.com' ([Errno -2] Name or service not known)"))
Error processing URL 5097 (https://walmartstores.com): HTTPSConnectionPool(host='walmartstores.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cc492b0>: Failed to resolve 'walmartstores.com' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5098 (https://bartarinha.ir): HTTPSConnectionPool(host='bartarinha.ir', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d846d20>, 'Connection to bartarinha.ir timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 5099 (https://gkvhfryrramj.com): HTTPSConnectionPool(host='gkvhfryrramj.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d85ce30>: Failed to resolve 'gkvhfryrramj.com' ([Errno -2] Name or service not known)"))
Processed 5100 URLs. Saving checkpoint...
Error processing URL 5102 (https://tv-torrent.club): HTTPSConnectionPool(host='tv-torrent.club', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d948410>: Failed to resolve 'tv-torrent.club' ([Errno -2] Name or service not known)"))
Error processing URL 5105 (https://statebankrewardz.com): HTTPSConnectionPool(host='statebankrewardz.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d94a3c0>: Failed to resolve 'statebankrewardz.com' ([Errno -5] No address associated with hostname)"))
Error processing URL 5107 (https://idol-blog.com): HTTPSConnectionPool(host='idol-blog.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b43d844a70>: Failed to establish a new connection: [Errno 111] Connection refused'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5111 (https://nntt.org): HTTPSConnectionPool(host='nntt.org', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d81ff80>, 'Connection to nntt.org timed out. (connect timeout=5)'))
Error processing URL 5115 (https://engageya.com): HTTPSConnectionPool(host='engageya.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cce7b00>: Failed to resolve 'engageya.com' ([Errno -5] No address associated with hostname)"))
Error processing URL 5116 (https://nwu.ac.za): HTTPSConnectionPool(host='nwu.ac.za', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce8c800>: Failed to resolve 'nwu.ac.za' ([Errno -5] No address associated with hostname)"))
Error processing URL 5120 (https://sougouwiki.com): HTTPSConnectionPool(host='sougouwiki.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b43cb08a10>: Failed to establish a new connection: [Errno 111] Connection refused'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Error processing URL 5122 (https://asianporn.sexy): HTTPSConnectionPool(host='asianporn.sexy', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d958e00>: Failed to resolve 'asianporn.sexy' ([Errno -2] Name or service not known)"))
Error processing URL 5129 (https://skinhub.com): HTTPSConnectionPool(host='skinhub.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce8e000>: Failed to resolve 'skinhub.com' ([Errno -5] No address associated with hostname)"))
Error processing URL 5130 (https://sspintrafmsmt.com): HTTPSConnectionPool(host='sspintrafmsmt.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d8469f0>, 'Connection to sspintrafmsmt.com timed out. (connect timeout=5)'))
Error processing URL 5132 (https://iauctb.ac.ir): HTTPSConnectionPool(host='iauctb.ac.ir', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d87f590>: Failed to resolve 'iauctb.ac.ir' ([Errno -3] Temporary failure in name resolution)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Error processing URL 5140 (https://gaokao789.com): HTTPSConnectionPool(host='gaokao789.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43cb0a9f0>, 'Connection to gaokao789.com timed out. (connect timeout=5)'))
Error processing URL 5141 (https://decathlon.ru): HTTPSConnectionPool(host='decathlon.ru', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d8a5850>: Failed to resolve 'decathlon.ru' ([Errno -5] No address associated with hostname)"))
Error processing URL 5142 (https://fotocommunity.de): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5143 (https://noticias24.com): HTTPSConnectionPool(host='noticias24.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'noticias24.com'. (_ssl.c:1010)")))
Error processing URL 5146 (https://dailyentertainments.com): HTTPSConnectionPool(host='dailyentertainments.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cde8fb0>: Failed to resolve 'dailyentertainments.com' ([Errno -2] Name or service not known)"))
Error processing URL 5149 (https://xvideos-d.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5152 (https://boombastis.com): HTTPSConnectionPool(host='boombastis.com', port=443): Read timed out. (read timeout=5)
Error processing URL 5153 (https://1f7de8569ea97f0614.com): HTTPSConnectionPool(host='1f7de8569ea97f0614.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d8f6ed0>: Failed to resolve '1f7de8569ea97f0614.com' ([Errno -2] Name or service not known)"))
Error processing URL 5156 (https://bancocredicoop.coop): HTTPSConnectionPool(host='bancocredicoop.coop', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43ce5e630>, 'Connection to bancocredicoop.coop timed out. (connect timeout=5)'))
Error processing URL 5158 (https://junbi-tracker.com): HTTPSConnectionPool(host='junbi-tracker.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b43d8f5280>: Failed to establish a new connection: [Errno 113] No route to host'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Error processing URL 5161 (https://vitalworldnews.com): HTTPSConnectionPool(host='vitalworldnews.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b43d95a090>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error processing URL 5164 (https://niazerooz.com): HTTPSConnectionPool(host='niazerooz.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43ceb1e50>, 'Connection to niazerooz.com timed out. (connect timeout=5)'))
Error processing URL 5165 (https://thebuzztube.com): HTTPSConnectionPool(host='thebuzztube.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d93ad20>: Failed to resolve 'thebuzztube.com' ([Errno -2] Name or service not known)"))
Error processing URL 5167 (https://ps4ux.com): HTTPSConnectionPool(host='ps4ux.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cae19a0>: Failed to resolve 'ps4ux.com' ([Errno -2] Name or service not known)"))
Error processing URL 5169 (https://gongchang.com): HTTPSConnectionPool(host='gongchang.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1010)')))
Error processing URL 5170 (https://ntpc.edu.tw): HTTPSConnectionPool(host='ntpc.edu.tw', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d87e840>: Failed to resolve 'ntpc.edu.tw' ([Errno -5] No address associated with hostname)"))
Error processing URL 5171 (https://secure-finder.org): HTTPSConnectionPool(host='secure-finder.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1010)')))
Error processing URL 5174 (https://emasti.pk): HTTPSConnectionPool(host='emasti.pk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b43d8f59a0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error processing URL 5176 (https://51edu.com): HTTPSConnectionPool(host='51edu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43cae1f10>, 'Connection to 51edu.com timed out. (connect timeout=5)'))
Error processing URL 5177 (https://oyun.se): HTTPSConnectionPool(host='robot.parktons.com', port=443): Max retries exceeded with url: /?host=oyun.se&next=/ (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1010)')))
Error processing URL 5178 (https://realtimepolitics.com): HTTPSConnectionPool(host='realtimepolitics.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d959d90>, 'Connection to realtimepolitics.com timed out. (connect timeout=5)'))
Error processing URL 5180 (https://justporno.sex): HTTPSConnectionPool(host='justporno.sex', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d8a7080>: Failed to resolve 'justporno.sex' ([Errno -2] Name or service not known)"))
Error processing URL 5182 (https://dizimag2.co): HTTPSConnectionPool(host='dizimag2.co', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d949670>: Failed to resolve 'dizimag2.co' ([Errno -2] Name or service not known)"))
Error processing URL 5186 (https://pythontab.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5188 (https://hokudai.ac.jp): HTTPSConnectionPool(host='hokudai.ac.jp', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d93b380>, 'Connection to hokudai.ac.jp timed out. (connect timeout=5)'))
Error processing URL 5191 (https://automoneymaker.co): HTTPSConnectionPool(host='automoneymaker.co', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ceb2720>: Failed to resolve 'automoneymaker.co' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Processed 5200 URLs. Saving checkpoint...
Error processing URL 5202 (https://gigporno-video.org): HTTPSConnectionPool(host='gigporno-video.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d93b080>: Failed to resolve 'gigporno-video.org' ([Errno -2] Name or service not known)"))
Error processing URL 5203 (https://orion-code-access.net): HTTPSConnectionPool(host='orion-code-access.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b464f1b560>: Failed to resolve 'orion-code-access.net' ([Errno -2] Name or service not known)"))
Error processing URL 5204 (https://daumcdn.net): HTTPSConnectionPool(host='daumcdn.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d81c920>: Failed to resolve 'daumcdn.net' ([Errno -5] No address associated with hostname)"))
Error processing URL 5206 (https://onlinetraffickrouting.com): HTTPSConnectionPool(host='onlinetraffickrouting.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ceb35c0>: Failed to resolve 'onlinetraffickrouting.com' ([Errno -2] Name or service not known)"))
Error processing URL 5209 (https://gba.gov.ar): HTTPSConnectionPool(host='gba.gov.ar', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d81f500>, 'Connection to gba.gov.ar timed out. (connect timeout=5)'))
Error processing URL 5210 (https://gimi.gdn): HTTPSConnectionPool(host='gimi.gdn', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ceb2ba0>: Failed to resolve 'gimi.gdn' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 5215 (https://netcoc.com): HTTPSConnectionPool(host='netcoc.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'netcoc.com'. (_ssl.c:1010)")))
Error processing URL 5217 (https://6arbyat.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5227 (https://urodakt.com): HTTPSConnectionPool(host='urodakt.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d85ffe0>: Failed to resolve 'urodakt.com' ([Errno -2] Name or service not known)"))
Error processing URL 5229 (https://licalup.accountant): HTTPSConnectionPool(host='licalup.accountant', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d87fb90>: Failed to resolve 'licalup.accountant' ([Errno -2] Name or service not known)"))
Error processing URL 5231 (https://avea.com.tr): HTTPSConnectionPool(host='avea.com.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)')))
Error processing URL 5241 (https://voluumtrk.com): HTTPSConnectionPool(host='voluumtrk.com', port=443): Read timed out. (read timeout=5)
Error processing URL 5248 (https://instamp3.me): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5258 (https://omerta.is): HTTPSConnectionPool(host='omerta.is', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce5cc80>: Failed to resolve 'omerta.is' ([Errno -2] Name or service not known)"))
Error processing URL 5260 (https://swatgeneration.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5268 (https://virginia.gov): HTTPSConnectionPool(host='virginia.gov', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)')))
Error processing URL 5270 (https://ichacha.net): HTTPSConnectionPool(host='ichacha.net', port=443): Read timed out. (read timeout=5)
Error processing URL 5271 (https://mp3mad.com): HTTPSConnectionPool(host='mp3mad.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce5da00>: Failed to resolve 'mp3mad.com' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 5272 (https://banking4you.it): HTTPSConnectionPool(host='banking4you.it', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d8d2f00>: Failed to resolve 'banking4you.it' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5286 (https://it1352.com): HTTPSConnectionPool(host='it1352.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43ce8e8d0>, 'Connection to it1352.com timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5289 (https://guangdiu.com): HTTPConnectionPool(host='216.58.200.46', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x79b43d846930>, 'Connection to 216.58.200.46 timed out. (connect timeout=5)'))
Error processing URL 5292 (https://buhaoting.com): HTTPSConnectionPool(host='buhaoting.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1010)')))
Error processing URL 5296 (https://cikax.xyz): HTTPSConnectionPool(host='cikax.xyz', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43c9f6420>: Failed to resolve 'cikax.xyz' ([Errno -2] Name or service not known)"))
Error processing URL 5297 (https://dfpan.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Processed 5300 URLs. Saving checkpoint...
Error processing URL 5300 (https://abplus.ir): HTTPSConnectionPool(host='abplus.ir', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cb08d40>: Failed to resolve 'abplus.ir' ([Errno -3] Temporary failure in name resolution)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 5301 (https://chedot.com): HTTPSConnectionPool(host='chedot.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'chedot.com'. (_ssl.c:1010)")))
Error processing URL 5302 (https://parenting.com): HTTPSConnectionPool(host='parenting.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43cdea030>, 'Connection to parenting.com timed out. (connect timeout=5)'))
Error processing URL 5305 (https://rus24.tv): HTTPSConnectionPool(host='rus24.tv', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cacc740>: Failed to resolve 'rus24.tv' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Error processing URL 5308 (https://sendfile.su): HTTPSConnectionPool(host='sendfile.su', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b43ca74950>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error processing URL 5310 (https://qlwb.com.cn): HTTPSConnectionPool(host='qlwb.com.cn', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43da89f40>, 'Connection to qlwb.com.cn timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5318 (https://blogsky.com): HTTPSConnectionPool(host='blogsky.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43da89c10>, 'Connection to blogsky.com timed out. (connect timeout=5)'))
Error processing URL 5321 (https://themusicz.com): HTTPSConnectionPool(host='themusicz.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d917980>: Failed to resolve 'themusicz.com' ([Errno -2] Name or service not known)"))
Error processing URL 5324 (https://libgen.io): HTTPSConnectionPool(host='libgen.io', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b464f6a7b0>: Failed to resolve 'libgen.io' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5327 (https://megafilmestop.org): HTTPSConnectionPool(host='megafilmestop.org', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d916a20>, 'Connection to megafilmestop.org timed out. (connect timeout=5)'))
Error processing URL 5328 (https://divar.ir): HTTPSConnectionPool(host='divar.ir', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43ce18890>, 'Connection to divar.ir timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 5330 (https://xjtu.edu.cn): HTTPSConnectionPool(host='xjtu.edu.cn', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43c8fd160>: Failed to resolve 'xjtu.edu.cn' ([Errno -5] No address associated with hostname)"))
Error processing URL 5334 (https://shglegle.com): HTTPSConnectionPool(host='shglegle.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce18380>: Failed to resolve 'shglegle.com' ([Errno -2] Name or service not known)"))
Error processing URL 5336 (https://modares.ac.ir): HTTPSConnectionPool(host='modares.ac.ir', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43ca76f60>, 'Connection to modares.ac.ir timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 5337 (https://nseindia.com): HTTPSConnectionPool(host='nseindia.com', port=443): Read timed out. (read timeout=5)
Error processing URL 5341 (https://adobelogin.com): HTTPSConnectionPool(host='adobelogin.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'adobelogin.com'. (_ssl.c:1010)")))
Error processing URL 5343 (https://pontofrio.com.br): HTTPSConnectionPool(host='pontofrio.com.br', port=443): Read timed out. (read timeout=5)
Error processing URL 5348 (https://law.go.kr): ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Error processing URL 5350 (https://antarvasnasexstories.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5352 (https://hrsmart.com): HTTPSConnectionPool(host='hrsmart.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d93b500>: Failed to resolve 'hrsmart.com' ([Errno -5] No address associated with hostname)"))
Error processing URL 5353 (https://gallery.ru): HTTPSConnectionPool(host='gallery.ru', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cb771a0>: Failed to resolve 'gallery.ru' ([Errno -2] Name or service not known)"))
Error processing URL 5358 (https://billmscurlrev.com): HTTPSConnectionPool(host='billmscurlrev.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d8d3b90>: Failed to resolve 'billmscurlrev.com' ([Errno -2] Name or service not known)"))
Error processing URL 5361 (https://animalog.biz): HTTPSConnectionPool(host='animalog.biz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1010)')))
Error processing URL 5363 (https://lxax.com): HTTPSConnectionPool(host='lxax.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43cde9760>, 'Connection to lxax.com timed out. (connect timeout=5)'))
Error processing URL 5366 (https://republic.ru): HTTPSConnectionPool(host='republic.ru', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ca16540>: Failed to resolve 'republic.ru' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Error processing URL 5370 (https://pornoid.com): HTTPSConnectionPool(host='pornoid.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cb74fe0>: Failed to resolve 'pornoid.com' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5379 (https://espnfcasia.com): HTTPSConnectionPool(host='espnfcasia.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'espnfcasia.com'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5382 (https://adrunnr.com): HTTPSConnectionPool(host='adrunnr.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d87c260>: Failed to resolve 'adrunnr.com' ([Errno -5] No address associated with hostname)"))
Error processing URL 5384 (https://harrods.com): HTTPSConnectionPool(host='www.harrods.com', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5385 (https://segundamano.mx): HTTPSConnectionPool(host='segundamano.mx', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cbc9160>: Failed to resolve 'segundamano.mx' ([Errno -5] No address associated with hostname)"))
Error processing URL 5387 (https://partners.org): HTTPSConnectionPool(host='partners.org', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d87f740>, 'Connection to partners.org timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5389 (https://speedy.com.ar): HTTPSConnectionPool(host='speedy.com.ar', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'speedy.com.ar'. (_ssl.c:1010)")))
Error processing URL 5393 (https://imsforex.com): HTTPSConnectionPool(host='imsforex.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43cae1190>, 'Connection to imsforex.com timed out. (connect timeout=5)'))
Processed 5400 URLs. Saving checkpoint...
Error processing URL 5405 (https://zhicheng.com): HTTPSConnectionPool(host='zhicheng.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b44caf0470>: Failed to resolve 'zhicheng.com' ([Errno -2] Name or service not known)"))
Error processing URL 5407 (https://cbec.gov.in): HTTPSConnectionPool(host='cbec.gov.in', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'cbec.gov.in'. (_ssl.c:1010)")))
Error processing URL 5408 (https://metacafe.com): HTTPSConnectionPool(host='metacafe.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43b8c0a10>: Failed to resolve 'metacafe.com' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 5412 (https://telebank.co.il): HTTPSConnectionPool(host='telebank.co.il', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cdea690>: Failed to resolve 'telebank.co.il' ([Errno -5] No address associated with hostname)"))
Error processing URL 5414 (https://shomanews.com): HTTPSConnectionPool(host='shomanews.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43b8c0770>, 'Connection to shomanews.com timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5417 (https://casacinema.video): HTTPSConnectionPool(host='casacinema.video', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ca77a10>: Failed to resolve 'casacinema.video' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5426 (https://garbarino.com): HTTPSConnectionPool(host='garbarino.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cae1130>: Failed to resolve 'garbarino.com' ([Errno -5] No address associated with hostname)"))
Error processing URL 5427 (https://missyusa.com): HTTPSConnectionPool(host='missyusa.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)')))
Error processing URL 5431 (https://hamgardi.com): HTTPSConnectionPool(host='hamgardi.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43cb08b30>, 'Connection to hamgardi.com timed out. (connect timeout=5)'))
Error processing URL 5435 (https://thailandnews.bid): HTTPSConnectionPool(host='thailandnews.bid', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ddaeed0>: Failed to resolve 'thailandnews.bid' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 113] No route to host

Error processing URL 5438 (https://pars.host): HTTPSConnectionPool(host='pars.host', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43ce1afc0>, 'Connection to pars.host timed out. (connect timeout=5)'))
Error processing URL 5440 (https://giftdervy.stream): HTTPSConnectionPool(host='giftdervy.stream', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b464f4ac00>: Failed to resolve 'giftdervy.stream' ([Errno -2] Name or service not known)"))
Error processing URL 5444 (https://kds.media): HTTPSConnectionPool(host='kds.media', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cbcb080>: Failed to resolve 'kds.media' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5460 (https://manga-mura.net): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5461 (https://webrootanywhere.com): HTTPSConnectionPool(host='webrootanywhere.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'webrootanywhere.com'. (_ssl.c:1010)")))
Error processing URL 5465 (https://h65sd.com): HTTPSConnectionPool(host='h65sd.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cb75d30>: Failed to resolve 'h65sd.com' ([Errno -2] Name or service not known)"))
Error processing URL 5466 (https://torrentz2.me): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5470 (https://olpair.com): HTTPSConnectionPool(host='olpair.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'olpair.com'. (_ssl.c:1010)")))
Error processing URL 5472 (https://mystartsearch.com): HTTPSConnectionPool(host='mystartsearch.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1010)')))
Error processing URL 5475 (https://israbox.plus): HTTPSConnectionPool(host='israbox.plus', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d81fb90>: Failed to resolve 'israbox.plus' ([Errno -2] Name or service not known)"))
Error processing URL 5479 (https://tjpr.jus.br): HTTPSConnectionPool(host='tjpr.jus.br', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b464f56c00>: Failed to resolve 'tjpr.jus.br' ([Errno -5] No address associated with hostname)"))
Error processing URL 5484 (https://lovetvshow.info): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5487 (https://shopandship.com): HTTPSConnectionPool(host='shopandship.com', port=443): Read timed out. (read timeout=5)
Error processing URL 5489 (https://trafficbaike1.top): HTTPSConnectionPool(host='trafficbaike1.top', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cbc9a30>: Failed to resolve 'trafficbaike1.top' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 5491 (https://kissmanga.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5495 (https://gaym.jp): HTTPSConnectionPool(host='gaym.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'gaym.jp'. (_ssl.c:1010)")))
Processed 5500 URLs. Saving checkpoint...
Error processing URL 5506 (https://etmall.com.tw): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5508 (https://elustaz.com): HTTPSConnectionPool(host='elustaz.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43c9f6090>: Failed to resolve 'elustaz.com' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 5510 (https://fwfgbhjhnlkv.com): HTTPSConnectionPool(host='fwfgbhjhnlkv.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cde9a90>: Failed to resolve 'fwfgbhjhnlkv.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5526 (https://filmywap.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5531 (https://eastcoastdaily.com): HTTPSConnectionPool(host='eastcoastdaily.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cae3ef0>: Failed to resolve 'eastcoastdaily.com' ([Errno -5] No address associated with hostname)"))
Error processing URL 5533 (https://gooood.hk): HTTPSConnectionPool(host='gooood.hk', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1010)')))
Error processing URL 5534 (https://vinmanager.com): HTTPSConnectionPool(host='vinmanager.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'vinmanager.com'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5539 (https://rj.gov.br): HTTPSConnectionPool(host='rj.gov.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'rj.gov.br'. (_ssl.c:1010)")))
Error processing URL 5546 (https://8drama.ru): HTTPSConnectionPool(host='robot.parktons.com', port=443): Max retries exceeded with url: /?host=8drama.ru&next=/ (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1010)')))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5548 (https://skymovies.im): HTTPSConnectionPool(host='skymovies.im', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43b848050>: Failed to resolve 'skymovies.im' ([Errno -2] Name or service not known)"))
Error processing URL 5549 (https://ipa.go.jp): HTTPSConnectionPool(host='ipa.go.jp', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43c8fe2d0>: Failed to resolve 'ipa.go.jp' ([Errno -5] No address associated with hostname)"))
Error processing URL 5552 (https://91watch.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5555 (https://saitebi.ge): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 113] No route to host

Error processing URL 5560 (https://adliran.ir): HTTPSConnectionPool(host='adliran.ir', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43c94f860>: Failed to resolve 'adliran.ir' ([Errno -3] Temporary failure in name resolution)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 5561 (https://wushare.com): HTTPSConnectionPool(host='wushare.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b43d95bec0>: Failed to establish a new connection: [Errno 111] Connection refused'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 104] Connection reset by peer
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5566 (https://5acbd.com): HTTPSConnectionPool(host='5acbd.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b43c9271a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error processing URL 5567 (https://yasdl.com): HTTPSConnectionPool(host='yasdl.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d95bfb0>, 'Connection to yasdl.com timed out. (connect timeout=5)'))
Error processing URL 5570 (https://metu.edu.tr): HTTPSConnectionPool(host='metu.edu.tr', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'metu.edu.tr'. (_ssl.c:1010)")))
Error processing URL 5579 (https://sm.de): HTTPSConnectionPool(host='sm.de', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1010)')))
Error processing URL 5580 (https://wec663.com): HTTPSConnectionPool(host='wec663.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ca16b10>: Failed to resolve 'wec663.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5585 (https://gonews24.com): HTTPSConnectionPool(host='gonews24.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43b8c00e0>, 'Connection to gonews24.com timed out. (connect timeout=5)'))
Error processing URL 5587 (https://civilica.com): HTTPSConnectionPool(host='civilica.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ca142c0>: Failed to resolve 'civilica.com' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 5590 (https://eetimes.com): HTTPSConnectionPool(host='www.eetimes.com', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5599 (https://mymaths.co.uk): HTTPSConnectionPool(host='mymaths.co.uk', port=443): Read timed out. (read timeout=5)
Processed 5600 URLs. Saving checkpoint...

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5602 (https://usnews.com): HTTPSConnectionPool(host='usnews.com', port=443): Read timed out. (read timeout=5)
Error processing URL 5605 (https://kt51.com): HTTPSConnectionPool(host='kt51.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'kt51.com'. (_ssl.c:1010)")))
Error processing URL 5607 (https://mkcl.org): HTTPSConnectionPool(host='mkcl.org', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43c927c50>, 'Connection to mkcl.org timed out. (connect timeout=5)'))
Error processing URL 5616 (https://dohillright.com): HTTPSConnectionPool(host='dohillright.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cce6fc0>: Failed to resolve 'dohillright.com' ([Errno -2] Name or service not known)"))
Error processing URL 5620 (https://gsurl.in): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5622 (https://seedpeer.eu): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5624 (https://privacyassistant.net): HTTPSConnectionPool(host='privacyassistant.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce8fce0>: Failed to resolve 'privacyassistant.net' ([Errno -2] Name or service not known)"))
Error processing URL 5626 (https://9anime.is): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5627 (https://bhu.co.kr): HTTPSConnectionPool(host='bhu.co.kr', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d959af0>, 'Connection to bhu.co.kr timed out. (connect timeout=5)'))
Error processing URL 5628 (https://p5w.net): HTTPSConnectionPool(host='p5w.net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b43ce8c590>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error processing URL 5629 (https://adidas-group.com): HTTPSConnectionPool(host='adidas-group.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'adidas-group.com'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5630 (https://takelessons.com): HTTPSConnectionPool(host='takelessons.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce8c260>: Failed to resolve 'takelessons.com' ([Errno -5] No address associated with hostname)"))
Error processing URL 5631 (https://ahgame.com): HTTPSConnectionPool(host='ahgame.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43ce8e840>, 'Connection to ahgame.com timed out. (connect timeout=5)'))
Error processing URL 5633 (https://56568.com): HTTPSConnectionPool(host='56568.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43c9a5bb0>, 'Connection to 56568.com timed out. (connect timeout=5)'))
Error processing URL 5634 (https://drakorindo.id): HTTPSConnectionPool(host='drakorindo.id', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43c9a75f0>: Failed to resolve 'drakorindo.id' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 113] No route to host

Error processing URL 5637 (https://onlinecreditcenter6.com): HTTPSConnectionPool(host='onlinecreditcenter6.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ceb39e0>: Failed to resolve 'onlinecreditcenter6.com' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5639 (https://beniculturali.it): HTTPSConnectionPool(host='beniculturali.it', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d9595e0>: Failed to resolve 'beniculturali.it' ([Errno -5] No address associated with hostname)"))
Error processing URL 5641 (https://state.md.us): HTTPSConnectionPool(host='state.md.us', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43cce7bf0>, 'Connection to state.md.us timed out. (connect timeout=5)'))
Error processing URL 5642 (https://500px.org): HTTPSConnectionPool(host='500px.org', port=443): Read timed out. (read timeout=5)
Error processing URL 5643 (https://cccs.edu): HTTPSConnectionPool(host='cccs.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)')))
Error processing URL 5649 (https://tnau.ac.in): HTTPSConnectionPool(host='tnau.ac.in', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43ca17740>, 'Connection to tnau.ac.in timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5671 (https://easy-firmware.com): HTTPSConnectionPool(host='easy-firmware.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da88c80>: Failed to resolve 'easy-firmware.com' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 5672 (https://xmuzic.me): HTTPSConnectionPool(host='xmuzic.me', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da88740>: Failed to resolve 'xmuzic.me' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5678 (https://pc-koubou.jp): HTTPSConnectionPool(host='pc-koubou.jp', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'pc-koubou.jp'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 5688 (https://hd-kinomax.org): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5689 (https://popcarpet.com): HTTPSConnectionPool(host='popcarpet.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce5f7a0>: Failed to resolve 'popcarpet.com' ([Errno -2] Name or service not known)"))
Error processing URL 5691 (https://myfreemp3.click): HTTPSConnectionPool(host='myfreemp3.click', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43c8ff530>: Failed to resolve 'myfreemp3.click' ([Errno -5] No address associated with hostname)"))
Error processing URL 5696 (https://cafemovie.me): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Processed 5700 URLs. Saving checkpoint...
Error processing URL 5707 (https://iranjavanmusic.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5708 (https://wozhongla.com): HTTPSConnectionPool(host='wozhongla.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43c9c9850>, 'Connection to wozhongla.com timed out. (connect timeout=5)'))
Error processing URL 5709 (https://embedupload.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5710 (https://tas.gov.au): HTTPSConnectionPool(host='tas.gov.au', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43ce12480>, 'Connection to tas.gov.au timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5715 (https://f8260adbf8558d6.com): HTTPSConnectionPool(host='f8260adbf8558d6.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce12180>: Failed to resolve 'f8260adbf8558d6.com' ([Errno -2] Name or service not known)"))
Error processing URL 5716 (https://yahui.cc): HTTPSConnectionPool(host='yahui.cc', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43cb0bb30>, 'Connection to yahui.cc timed out. (connect timeout=5)'))
Error processing URL 5719 (https://taian7.com): HTTPSConnectionPool(host='taian7.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'taian7.com'. (_ssl.c:1010)")))
Error processing URL 5724 (https://jav789.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5725 (https://teamusa.org): HTTPSConnectionPool(host='www.teamusa.org', port=443): Read timed out. (read timeout=5)
Error processing URL 5726 (https://sekret-bogatstva.ru): HTTPSConnectionPool(host='sekret-bogatstva.ru', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ca1f380>: Failed to resolve 'sekret-bogatstva.ru' ([Errno -2] Name or service not known)"))
Error processing URL 5733 (https://payulatam.com): HTTPSConnectionPool(host='payulatam.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce1b260>: Failed to resolve 'payulatam.com' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5738 (https://lan.com): HTTPSConnectionPool(host='lan.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43da8abd0>, 'Connection to lan.com timed out. (connect timeout=5)'))
Error processing URL 5739 (https://emulator.online): HTTPSConnectionPool(host='emulator.online', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1010)')))
Error processing URL 5743 (https://carrosnaweb.com.br): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5748 (https://pdfonline.com): HTTPSConnectionPool(host='pdfonline.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)')))
Error processing URL 5749 (https://malaysiable.news): HTTPSConnectionPool(host='malaysiable.news', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43c9c8740>: Failed to resolve 'malaysiable.news' ([Errno -2] Name or service not known)"))
Error processing URL 5751 (https://tnea.ac.in): HTTPSConnectionPool(host='tnea.ac.in', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b464f19070>: Failed to resolve 'tnea.ac.in' ([Errno -2] Name or service not known)"))
Error processing URL 5759 (https://wayport.net): HTTPSConnectionPool(host='wayport.net', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b47171e870>, 'Connection to wayport.net timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5763 (https://aport.ru): HTTPSConnectionPool(host='aport.ru', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43b84b140>: Failed to resolve 'aport.ru' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 5771 (https://a24.az): HTTPSConnectionPool(host='a24.az', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43b8c0620>: Failed to resolve 'a24.az' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5776 (https://job592.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5777 (https://mortgage-application.net): HTTPSConnectionPool(host='mortgage-application.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mortgage-application.net'. (_ssl.c:1010)")))
Error processing URL 5780 (https://kmeiju.net): HTTPSConnectionPool(host='kmeiju.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d8f68a0>: Failed to resolve 'kmeiju.net' ([Errno -2] Name or service not known)"))
Error processing URL 5782 (https://xn--cckea5a6cidcbh6ce7ghug17a2ge3aht3nwigef51658aw7kd.com): HTTPSConnectionPool(host='xn--cckea5a6cidcbh6ce7ghug17a2ge3aht3nwigef51658aw7kd.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43c9a7620>: Failed to resolve 'xn--cckea5a6cidcbh6ce7ghug17a2ge3aht3nwigef51658aw7kd.com' ([Errno -2] Name or service not known)"))
Error processing URL 5790 (https://newchic.com): HTTPSConnectionPool(host='newchic.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cb751c0>: Failed to resolve 'newchic.com' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Processed 5800 URLs. Saving checkpoint...
Error processing URL 5803 (https://5iyingxiao.com): HTTPSConnectionPool(host='5iyingxiao.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b43b8c0830>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error processing URL 5805 (https://assistindoanimesonline.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5808 (https://bozhong.com): HTTPSConnectionPool(host='bozhong.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43b8c3b60>, 'Connection to bozhong.com timed out. (connect timeout=5)'))
Error processing URL 5809 (https://upresults.nic.in): HTTPSConnectionPool(host='upresults.nic.in', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1010)')))
Error processing URL 5810 (https://blobar.org): HTTPSConnectionPool(host='blobar.org', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43cae2ed0>, 'Connection to blobar.org timed out. (connect timeout=5)'))
Error processing URL 5814 (https://zdfx.net): HTTPSConnectionPool(host='zdfx.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ca162d0>: Failed to resolve 'zdfx.net' ([Errno -5] No address associated with hostname)"))
Error processing URL 5815 (https://anser.ne.jp): HTTPSConnectionPool(host='anser.ne.jp', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43c9a59a0>: Failed to resolve 'anser.ne.jp' ([Errno -5] No address associated with hostname)"))
Error processing URL 5820 (https://starcrafthighlight.com): HTTPSConnectionPool(host='starcrafthighlight.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b464f49d30>: Failed to resolve 'starcrafthighlight.com' ([Errno -2] Name or service not known)"))
Error processing URL 5821 (https://free-rutor.org): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5823 (https://suning.com): HTTPSConnectionPool(host='suning.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1010)')))
Error processing URL 5830 (https://ruseddown2.pw): HTTPSConnectionPool(host='ruseddown2.pw', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43c9c87d0>: Failed to resolve 'ruseddown2.pw' ([Errno -2] Name or service not known)"))
Error processing URL 5835 (https://bombuj.eu): HTTPSConnectionPool(host='bombuj.eu', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b44cdefd70>, 'Connection to bombuj.eu timed out. (connect timeout=5)'))
Error processing URL 5838 (https://7bab60879a3.com): HTTPSConnectionPool(host='7bab60879a3.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ceb3710>: Failed to resolve '7bab60879a3.com' ([Errno -2] Name or service not known)"))
Error processing URL 5842 (https://kita-kore.com): HTTPSConnectionPool(host='kita-kore.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b464f4ae10>, 'Connection to kita-kore.com timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Error processing URL 5847 (https://llss.me): HTTPSConnectionPool(host='llss.me', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ceb1d30>: Failed to resolve 'llss.me' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5860 (https://3m.com): HTTPSConnectionPool(host='www.3m.com', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5873 (https://cleanmypc.co): HTTPSConnectionPool(host='cleanmypc.co', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce13c80>: Failed to resolve 'cleanmypc.co' ([Errno -2] Name or service not known)"))
Error processing URL 5878 (https://ebsamen.com): HTTPSConnectionPool(host='ebsamen.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ceb3830>: Failed to resolve 'ebsamen.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5882 (https://smitehighlights.com): HTTPSConnectionPool(host='smitehighlights.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cacddf0>: Failed to resolve 'smitehighlights.com' ([Errno -2] Name or service not known)"))
Error processing URL 5883 (https://punjab.gov.pk): HTTPSConnectionPool(host='punjab.gov.pk', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43cacfef0>, 'Connection to punjab.gov.pk timed out. (connect timeout=5)'))
Error processing URL 5886 (https://groupon.fr): HTTPSConnectionPool(host='www.groupon.fr', port=443): Read timed out. (read timeout=5)
Error processing URL 5888 (https://anzhuotan.com): HTTPSConnectionPool(host='anzhuotan.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da89700>: Failed to resolve 'anzhuotan.com' ([Errno -2] Name or service not known)"))
Error processing URL 5889 (https://ca800.com): HTTPSConnectionPool(host='ca800.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43d915c40>, 'Connection to ca800.com timed out. (connect timeout=5)'))
Error processing URL 5891 (https://tlcthai.com): HTTPSConnectionPool(host='tlcthai.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d85cf80>: Failed to resolve 'tlcthai.com' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 5893 (https://cipc.co.za): HTTPSConnectionPool(host='cipc.co.za', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce5fef0>: Failed to resolve 'cipc.co.za' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Processed 5900 URLs. Saving checkpoint...
Error processing URL 5900 (https://tisub.biz): HTTPSConnectionPool(host='tisub.biz', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b44c1e6de0>: Failed to resolve 'tisub.biz' ([Errno -2] Name or service not known)"))
Error processing URL 5904 (https://qzzn.com): HTTPSConnectionPool(host='qzzn.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b43d8f7410>: Failed to establish a new connection: [Errno 111] Connection refused'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5913 (https://elbowviewpoint.com): HTTPSConnectionPool(host='elbowviewpoint.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d958770>: Failed to resolve 'elbowviewpoint.com' ([Errno -2] Name or service not known)"))
Error processing URL 5916 (https://luyinla.com): HTTPSConnectionPool(host='luyinla.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b464f60b60>, 'Connection to luyinla.com timed out. (connect timeout=5)'))
Error processing URL 5921 (https://kinogo-onlain.club): HTTPSConnectionPool(host='kinogo-onlain.club', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d8d3c50>: Failed to resolve 'kinogo-onlain.club' ([Errno -2] Name or service not known)"))
Error processing URL 5922 (https://zqnow.com): HTTPSConnectionPool(host='zqnow.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b464f6a7b0>, 'Connection to zqnow.com timed out. (connect timeout=5)'))
Error processing URL 5924 (https://bimmerfest.com): HTTPSConnectionPool(host='bimmerfest.com', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5926 (https://canal-plus.com): HTTPSConnectionPool(host='canal-plus.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_UNRECOGNIZED_NAME] tlsv1 unrecognized name (_ssl.c:1010)')))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 113] No route to host

Error processing URL 5931 (https://lottedfs.com): HTTPSConnectionPool(host='lottedfs.com', port=443): Read timed out. (read timeout=5)
Error processing URL 5942 (https://573.jp): HTTPSConnectionPool(host='573.jp', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43b8c0b60>: Failed to resolve '573.jp' ([Errno -5] No address associated with hostname)"))
Error processing URL 5946 (https://ldoceonline.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5947 (https://rakuten.com.tw): HTTPSConnectionPool(host='www.rakuten.com.tw', port=443): Read timed out. (read timeout=5)
Error processing URL 5949 (https://applyabroad.org): HTTPSConnectionPool(host='applyabroad.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b43d9172c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error processing URL 5950 (https://51hejia.com): HTTPSConnectionPool(host='51hejia.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1010)')))
Error processing URL 5951 (https://videoyoum7.com): HTTPSConnectionPool(host='videoyoum7.com', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5955 (https://angeinge.com): HTTPSConnectionPool(host='angeinge.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cb77770>: Failed to resolve 'angeinge.com' ([Errno -2] Name or service not known)"))
Error processing URL 5956 (https://educacion.es): HTTPSConnectionPool(host='educacion.es', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b43d8a6390>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error processing URL 5960 (https://craftsvilla.com): HTTPSConnectionPool(host='craftsvilla.com', port=443): Read timed out. (read timeout=5)
Error processing URL 5963 (https://jlonline.com): HTTPSConnectionPool(host='jlonline.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cb0afc0>: Failed to resolve 'jlonline.com' ([Errno -5] No address associated with hostname)"))
Error processing URL 5964 (https://kserieshd.com): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 5965 (https://sonicpdfconverter.com): HTTPSConnectionPool(host='sonicpdfconverter.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cb083b0>: Failed to resolve 'sonicpdfconverter.com' ([Errno -5] No address associated with hostname)"))
Error processing URL 5967 (https://bitmedianetwork.com): HTTPSConnectionPool(host='bitmedianetwork.com', port=443): Read timed out. (read timeout=5)
Error processing URL 5972 (https://sabresonicweb.com): HTTPSConnectionPool(host='sabresonicweb.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43cb08380>, 'Connection to sabresonicweb.com timed out. (connect timeout=5)'))
Error processing URL 5974 (https://mizuhobank.co.jp): HTTPSConnectionPool(host='mizuhobank.co.jp', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43af1e510>: Failed to resolve 'mizuhobank.co.jp' ([Errno -5] No address associated with hostname)"))
Error processing URL 5976 (https://epravesh.nic.in): HTTPSConnectionPool(host='epravesh.nic.in', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43af1eae0>, 'Connection to epravesh.nic.in timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 113] No route to host
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 5986 (https://sinhvienit.net): HTTPSConnectionPool(host='sinhvienit.net', port=443): Read timed out. (read timeout=5)
Error processing URL 5989 (https://sunsu521.com): HTTPSConnectionPool(host='sunsu521.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43af1e120>: Failed to resolve 'sunsu521.com' ([Errno -2] Name or service not known)"))
Error processing URL 5992 (https://mris.com): HTTPSConnectionPool(host='mris.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da8a750>: Failed to resolve 'mris.com' ([Errno -5] No address associated with hostname)"))
Error processing URL 5993 (https://fx678.com): HTTPSConnectionPool(host='fx678.com', port=443): Read timed out. (read timeout=5)
Error processing URL 5994 (https://ozs.cn): HTTPSConnectionPool(host='ozs.cn', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43c8fdac0>, 'Connection to ozs.cn timed out. (connect timeout=5)'))
Error processing URL 5996 (https://bjut.edu.cn): HTTPSConnectionPool(host='bjut.edu.cn', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43c8fe480>, 'Connection to bjut.edu.cn timed out. (connect timeout=5)'))
Error processing URL 5997 (https://anonymousnews.ru): Exceeded 30 redirects.
Error processing URL 5998 (https://jogossantacasa.pt): HTTPSConnectionPool(host='jogossantacasa.pt', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43b167d40>: Failed to resolve 'jogossantacasa.pt' ([Errno -5] No address associated with hostname)"))
Processed 6000 URLs. Saving checkpoint...
Error processing URL 6004 (https://securecode.com): HTTPSConnectionPool(host='securecode.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da8b350>: Failed to resolve 'securecode.com' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 6012 (https://rooxflwtrafms.com): HTTPSConnectionPool(host='rooxflwtrafms.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43cde80e0>: Failed to resolve 'rooxflwtrafms.com' ([Errno -2] Name or service not known)"))
Error processing URL 6019 (https://btbta.com): HTTPSConnectionPool(host='btbta.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b439fcdcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error processing URL 6020 (https://vlifeapp.com): HTTPSConnectionPool(host='vlifeapp.com', port=443): Read timed out. (read timeout=5)
Error processing URL 6023 (https://palimas.tv): HTTPSConnectionPool(host='palimas.tv', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b439ec5a00>: Failed to resolve 'palimas.tv' ([Errno -2] Name or service not known)"))
Error processing URL 6029 (https://streamlord.com): HTTPSConnectionPool(host='streamlord.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x79b464f5b860>: Failed to establish a new connection: [Errno 111] Connection refused'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 6034 (https://makeawesomelife.com): HTTPSConnectionPool(host='makeawesomelife.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b439e141a0>: Failed to resolve 'makeawesomelife.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 6036 (https://cnpq.br): HTTPSConnectionPool(host='cnpq.br', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1010)')))
Error processing URL 6037 (https://ncert.nic.in): ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Error processing URL 6039 (https://easy2date.net): HTTPSConnectionPool(host='easy2date.net', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ca76e10>: Failed to resolve 'easy2date.net' ([Errno -2] Name or service not known)"))
Error processing URL 6040 (https://payaneh.ir): HTTPSConnectionPool(host='payaneh.ir', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43ce19490>, 'Connection to payaneh.ir timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 6041 (https://yihaocar.com): HTTPSConnectionPool(host='yihaocar.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79b43ca752e0>, 'Connection to yihaocar.com timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 6044 (https://onesafe-software.com): HTTPSConnectionPool(host='onesafe-software.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1010)')))
Error processing URL 6045 (https://jkanime.co): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 6047 (https://allsingaporestuff.com): HTTPSConnectionPool(host='www.allsingaporestuff.com', port=443): Read timed out. (read timeout=5)
Error processing URL 6048 (https://wholesale-dress.it): HTTPSConnectionPool(host='wholesale-dress.it', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43ce1a210>: Failed to resolve 'wholesale-dress.it' ([Errno -2] Name or service not known)"))
Error processing URL 6052 (https://axisbank.co.in): HTTPSConnectionPool(host='axisbank.co.in', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b439dd78c0>: Failed to resolve 'axisbank.co.in' ([Errno -5] No address associated with hostname)"))
Error processing URL 6053 (https://bnonline.fi.cr): HTTPSConnectionPool(host='bnonline.fi.cr', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43da89dc0>: Failed to resolve 'bnonline.fi.cr' ([Errno -5] No address associated with hostname)"))
Error processing URL 6057 (https://marketo.com): HTTPSConnectionPool(host='business.adobe.com', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 6060 (https://adpop-1.com): HTTPSConnectionPool(host='adpop-1.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b439e99f10>: Failed to resolve 'adpop-1.com' ([Errno -2] Name or service not known)"))
Error processing URL 6063 (https://csspotlights.com): HTTPSConnectionPool(host='csspotlights.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b439cfaf00>: Failed to resolve 'csspotlights.com' ([Errno -2] Name or service not known)"))
Error processing URL 6066 (https://jwa.or.jp): HTTPSConnectionPool(host='jwa.or.jp', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b439e025d0>: Failed to resolve 'jwa.or.jp' ([Errno -5] No address associated with hostname)"))
Error processing URL 6068 (https://freepornhq.xxx): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 6070 (https://678pan.com): HTTPSConnectionPool(host='678pan.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1010)')))
Error processing URL 6071 (https://cao.go.jp): HTTPSConnectionPool(host='cao.go.jp', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b439f0f710>: Failed to resolve 'cao.go.jp' ([Errno -5] No address associated with hostname)"))
Error processing URL 6074 (https://keeplinks.eu): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 6077 (https://persianblog.ir): HTTPSConnectionPool(host='persianblog.ir', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b439f38470>: Failed to resolve 'persianblog.ir' ([Errno -3] Temporary failure in name resolution)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 6079 (https://7mm.tv): HTTPSConnectionPool(host='7mm.tv', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Error processing URL 6085 (https://timinternet.it): HTTPSConnectionPool(host='timinternet.it', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)')))
Error processing URL 6086 (https://kome.gdn): HTTPSConnectionPool(host='kome.gdn', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b43d8a76e0>: Failed to resolve 'kome.gdn' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 6087 (https://associatedbank.com): HTTPSConnectionPool(host='www.associatedbank.com', port=443): Read timed out. (read timeout=5)
Error processing URL 6093 (https://hbrsks.gov.cn): HTTPSConnectionPool(host='hbrsks.gov.cn', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b439fcff50>: Failed to resolve 'hbrsks.gov.cn' ([Errno -2] Name or service not known)"))
Error processing URL 6094 (https://dref.pw): HTTPSConnectionPool(host='dref.pw', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x79b439e6e0c0>: Failed to resolve 'dref.pw' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Processed 6100 URLs. Saving checkpoint...
Extraction complete!

In [2]:
#converting the list to dataframe
feature_names = ['Domain', 'Have_IP', 'Have_At', 'URL_Length', 'URL_Depth','Redirection',
                      'https_Domain', 'TinyURL', 'Prefix/Suffix', 'DNS_Record', 'Web_Traffic',
                      'Domain_Age', 'Domain_End', 'iFrame', 'Mouse_Over','Right_Click', 'Web_Forwards', 'Label']

# Load both files without headers (as they appear to be raw data)
df1 = pd.read_csv('legi_features_backup (1).csv', header=None, names=feature_names)
df2 = pd.read_csv('legi_features_backup (2).csv', header=None, names=feature_names)
df3 = pd.read_csv('legi_features_backup(3).csv', header=None, names=feature_names)
df4 = pd.read_csv('legi_features_backup(4).csv', header=None, names=feature_names)
df5 = pd.read_csv('legi_features_backup(5).csv', header=None, names=feature_names)

# Concatenate the dataframes
combined_df = pd.concat([df1, df2, df3, df4, df5], ignore_index=True)

combined_df.head()

,Domain,Have_IP,Have_At,URL_Length,URL_Depth,Redirection,https_Domain,TinyURL,Prefix/Suffix,DNS_Record,Web_Traffic,Domain_Age,Domain_End,iFrame,Mouse_Over,Right_Click,Web_Forwards,Label
0,graphicriver.net,0,0,1,1,0,0,0,0,0,1,1,1,0,0,1,0,0
1,ecnavi.jp,0,0,1,1,1,0,0,0,0,1,0,1,0,0,1,0,0
2,hubpages.com,0,0,1,1,0,0,0,0,0,1,0,1,0,0,1,0,0
3,extratorrent.cc,0,0,1,3,0,0,0,0,0,1,0,1,1,1,1,1,0
4,icicibank.com,0,0,1,3,0,0,0,0,0,1,0,1,0,0,1,0,0

In [3]:
combined_df.shape

(15000, 18)

In [4]:
# Storing the extracted legitimate URLs fatures to csv file
combined_df.to_csv('legitimate.csv', index=False)

## **4.2. Phishing URLs:**
Now, feature extraction is performed on phishing URLs.

In [ ]:
phishurl.shape

(15000, 8)

In [ ]:

#Extracting the feautres & storing them in a list
import requests
import csv
import os

phish_features = []
label = 1
start_index = 14100 # If you crash at 3500, change this to 3500 and run again!
total_urls = 15000
checkpoint_interval = 100

# Use a session to manage network resources efficiently
session = requests.Session()

# Create or prepare the CSV file for saving progress
csv_filename = "phish_features_backup(5).csv"

for i in range(start_index, total_urls):
    url = phishurl['url'][i]

    # Wrap the ENTIRE process for this URL in a try block
    try:
        response = session.get(url, timeout=5)
        features = featureExtraction(url, label, response)
    except Exception as e:
        # If ANYTHING goes wrong (network error, extraction error), catch it
        print(f"Error processing URL {i} ({url}): {e}")
        # Assuming your function can handle 'None' for a completely failed attempt
        try:
             features = featureExtraction(url, label, None)
        except Exception:
             # If even the fallback fails, append empty/null data so rows align
             features = {"url": url, "error": str(e)}

    phish_features.append(features)

    # Checkpoint: Save to CSV and clear memory every 100 URLs
    if (i + 1) % checkpoint_interval == 0 or (i + 1) == total_urls:
        print(f"Processed {i + 1} URLs. Saving checkpoint...")

        # Check if file exists so we only write headers once
        file_exists = os.path.isfile(csv_filename)

        with open(csv_filename, 'a', newline='', encoding='utf-8') as f:
            # Assuming 'features' is a dictionary. If it's a list, use csv.writer instead.
            if isinstance(features, dict):
                writer = csv.DictWriter(f, fieldnames=features.keys())
                if not file_exists:
                    writer.writeheader()
                writer.writerows(phish_features)
            else:
                writer = csv.writer(f)
                writer.writerows(phish_features)

        # Clear the list to free up RAM!
        phish_features = []

print("Extraction complete!")

Error processing URL 14103 (https://swissexpress.order-swiss.rest/180225185): HTTPSConnectionPool(host='swissexpress.order-swiss.rest', port=443): Max retries exceeded with url: /180225185 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7c70d708fef0>, 'Connection to swissexpress.order-swiss.rest timed out. (connect timeout=5)'))
Error processing URL 14105 (https://tafiole.appexpd-clients.com/as.php): HTTPSConnectionPool(host='tafiole.appexpd-clients.com', port=443): Max retries exceeded with url: /as.php (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d708f410>: Failed to resolve 'tafiole.appexpd-clients.com' ([Errno -2] Name or service not known)"))
Error processing URL 14106 (https://www.brtfs.cc/it): HTTPSConnectionPool(host='www.brtfs.cc', port=443): Max retries exceeded with url: /it (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6fa4b90>: Failed to resolve 'www.brtfs.cc' ([Errno -2] Name or service not known)"))
Error processing URL 14110 (https://tr.casbom9099.com/): HTTPSConnectionPool(host='tr.casbom9099.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d708fe00>: Failed to resolve 'tr.casbom9099.com' ([Errno -2] Name or service not known)"))
Error processing URL 14114 (https://mysetingadm-bnlportal.emtclinet.vip/LxyfjbtM0Xg0XTj3): HTTPSConnectionPool(host='mysetingadm-bnlportal.emtclinet.vip', port=443): Max retries exceeded with url: /LxyfjbtM0Xg0XTj3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d708f5f0>: Failed to resolve 'mysetingadm-bnlportal.emtclinet.vip' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14122 (https://aldakheelholding.com/apply): HTTPSConnectionPool(host='aldakheelholding.com', port=443): Max retries exceeded with url: /apply (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6e3f530>: Failed to resolve 'aldakheelholding.com' ([Errno -3] Temporary failure in name resolution)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14132 (https://impayevinci-sms.com/app): HTTPSConnectionPool(host='impayevinci-sms.com', port=443): Max retries exceeded with url: /app (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6e3eff0>: Failed to resolve 'impayevinci-sms.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14147 (https://app.biavantagem.info): HTTPSConnectionPool(host='app.biavantagem.info', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1010)')))
Error processing URL 14148 (https://kleinanzeigen.00070.icu/receive/05233421?mail=W1NXSUZUXQ%3D%3D&meta=rlWjMKWwLJ50LJqyVwb1YPWhLJ1yVwbvKUIxBQAwKUIxMwRjVSA3nJM0VR1unJkypvVfVzAbLKEsnJDvBv0kZQNmZwt0AGp3BGN3YPWmMKW2nJAyVwbvn2kynJ5uoacynJqyovVfVaE5pTHvBvWmq2yzqS9gLJyfMKVvsD%3D%3D): HTTPSConnectionPool(host='kleinanzeigen.00070.icu', port=443): Max retries exceeded with url: /receive/05233421?mail=W1NXSUZUXQ%3D%3D&meta=rlWjMKWwLJ50LJqyVwb1YPWhLJ1yVwbvKUIxBQAwKUIxMwRjVSA3nJM0VR1unJkypvVfVzAbLKEsnJDvBv0kZQNmZwt0AGp3BGN3YPWmMKW2nJAyVwbvn2kynJ5uoacynJqyovVfVaE5pTHvBvWmq2yzqS9gLJyfMKVvsD%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6efecc0>: Failed to resolve 'kleinanzeigen.00070.icu' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14151 (http://gram-wallet.org): HTTPSConnectionPool(host='gram-wallet.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1010)')))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14153 (https://cartaocontinente-ptrzns.cfd/pts/): HTTPSConnectionPool(host='cartaocontinente-ptrzns.cfd', port=443): Max retries exceeded with url: /pts/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6fa43e0>: Failed to resolve 'cartaocontinente-ptrzns.cfd' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14159 (https://laptitetaoette.clients-expd-fr.com/): HTTPSConnectionPool(host='laptitetaoette.clients-expd-fr.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7c70d6fa4410>, 'Connection to laptitetaoette.clients-expd-fr.com timed out. (connect timeout=5)'))
Error processing URL 14165 (https://nuauq.numina.cfd/gardxzb0xj5vMf6iwt69ht): HTTPSConnectionPool(host='nuauq.numina.cfd', port=443): Max retries exceeded with url: /gardxzb0xj5vMf6iwt69ht (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6efc050>: Failed to resolve 'nuauq.numina.cfd' ([Errno -2] Name or service not known)"))
Error processing URL 14166 (https://t.co/cLXXUmerER): HTTPSConnectionPool(host='cq13541.tw1.ru', port=443): Max retries exceeded with url: /web (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'cq13541.tw1.ru'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14172 (https://colisenvoi-relay.com/as.php): HTTPSConnectionPool(host='colisenvoi-relay.com', port=443): Max retries exceeded with url: /as.php (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d708e720>: Failed to resolve 'colisenvoi-relay.com' ([Errno -5] No address associated with hostname)"))
Error processing URL 14180 (http://allegrolokainie.conformation-1914.shop): HTTPConnectionPool(host='allegrolokainie.conformation-1914.shop', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c70d6efc0e0>: Failed to resolve 'allegrolokainie.conformation-1914.shop' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14189 (https://t.co/0T6YGRq4sE): HTTPSConnectionPool(host='vjjnvhk.life', port=443): Max retries exceeded with url: /us (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6efe2a0>: Failed to resolve 'vjjnvhk.life' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14197 (https://main.dk8b-info.eu/?de): HTTPSConnectionPool(host='main.dk8b-info.eu', port=443): Max retries exceeded with url: /?de (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f1e660>: Failed to resolve 'main.dk8b-info.eu' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Processed 14200 URLs. Saving checkpoint...
Error processing URL 14200 (https://rfortraders.com/ionokunden.de/index.html): HTTPSConnectionPool(host='rfortraders.com', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14218 (https://ovhfrance.com/FR658E5F2EZ560000/FR2025-17-12/): HTTPSConnectionPool(host='ovhfrance.com', port=443): Max retries exceeded with url: /FR658E5F2EZ560000/FR2025-17-12/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6fa4260>: Failed to resolve 'ovhfrance.com' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 14221 (https://kleinanzeigen.09152.icu/receive/472215091&ex=iframe&challenge=rlWcqvV6VyuuMREnrJIEF3WipQHjISjiVvjvL2yjnTIlqTI4qPV6VzcvqSOEMzgEpSqFJSu3CG0vYPW0LJpvBvWFH2clDyjiZmpkJQq5ZTyKHzf1GKAcHG09VvjvLJSxVwbvMKyXZTSKZJkWnz94GacMZ09RL3yBESI4GTcOq01dEKyBZmN9VvjvL2AuVwbvDIABEyb0oKW6MGuPFGOJozyuqx43q0IdHyqyFaR4Z3MOH05TJwEgpacyBQ0vsD%3D%3D): HTTPSConnectionPool(host='kleinanzeigen.09152.icu', port=443): Max retries exceeded with url: /receive/472215091&ex=iframe&challenge=rlWcqvV6VyuuMREnrJIEF3WipQHjISjiVvjvL2yjnTIlqTI4qPV6VzcvqSOEMzgEpSqFJSu3CG0vYPW0LJpvBvWFH2clDyjiZmpkJQq5ZTyKHzf1GKAcHG09VvjvLJSxVwbvMKyXZTSKZJkWnz94GacMZ09RL3yBESI4GTcOq01dEKyBZmN9VvjvL2AuVwbvDIABEyb0oKW6MGuPFGOJozyuqx43q0IdHyqyFaR4Z3MOH05TJwEgpacyBQ0vsD%3D%3D (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f41910>: Failed to resolve 'kleinanzeigen.09152.icu' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14227 (https://www.todayadvertising.co.in/plalan/webmai1): HTTPSConnectionPool(host='www.todayadvertising.co.in', port=443): Max retries exceeded with url: /plalan/webmai1 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70e0ce4620>: Failed to resolve 'www.todayadvertising.co.in' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14236 (https://enoiu.numina.cfd/HnodWnfEpQOjMnhEVdyubth): HTTPSConnectionPool(host='enoiu.numina.cfd', port=443): Max retries exceeded with url: /HnodWnfEpQOjMnhEVdyubth (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f419a0>: Failed to resolve 'enoiu.numina.cfd' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14244 (https://jko.igs.mybluehost.me/): HTTPSConnectionPool(host='jko.igs.mybluehost.me', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'jko.igs.mybluehost.me'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14249 (https://clwks.thrives.cfd/smojo): HTTPSConnectionPool(host='clwks.thrives.cfd', port=443): Max retries exceeded with url: /smojo (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f414c0>: Failed to resolve 'clwks.thrives.cfd' ([Errno -2] Name or service not known)"))
Error processing URL 14253 (https://fh4i5asf.icu/ra18gwae/5zwcEw/X8yKii): HTTPSConnectionPool(host='fh4i5asf.icu', port=443): Max retries exceeded with url: /ra18gwae/5zwcEw/X8yKii (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f1dcd0>: Failed to resolve 'fh4i5asf.icu' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14258 (https://baux.clients-smspickup.com/): HTTPSConnectionPool(host='baux.clients-smspickup.com', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14270 (https://eepsq.skyboltzone.cfd/NmodWnfEpLpjMnhEVdy45th): HTTPSConnectionPool(host='eepsq.skyboltzone.cfd', port=443): Max retries exceeded with url: /NmodWnfEpLpjMnhEVdy45th (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f1cf50>: Failed to resolve 'eepsq.skyboltzone.cfd' ([Errno -2] Name or service not known)"))
Error processing URL 14271 (https://service-bordereaufr.com/index.php): HTTPSConnectionPool(host='service-bordereaufr.com', port=443): Max retries exceeded with url: /index.php (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f1da60>: Failed to resolve 'service-bordereaufr.com' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 14273 (https://districtcourtsouth.com/): HTTPSConnectionPool(host='districtcourtsouth.com', port=443): Read timed out. (read timeout=5)
Error processing URL 14275 (http://evri.ene-fines.website): HTTPConnectionPool(host='evri.ene-fines.website', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c7100373320>: Failed to resolve 'evri.ene-fines.website' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Error processing URL 14279 (https://sp406530.sitebeat.crazydomains.com/): HTTPSConnectionPool(host='global_errors.sitebeat.crazydomains.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'global_errors.sitebeat.crazydomains.com'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14285 (https://willem.pickuppackets-expd.com/as.php): HTTPSConnectionPool(host='willem.pickuppackets-expd.com', port=443): Max retries exceeded with url: /as.php (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f41910>: Failed to resolve 'willem.pickuppackets-expd.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14288 (https://allegrolokalnie.pl-oferta32132.sbs/): HTTPSConnectionPool(host='allegrolokalnie.pl-oferta32132.sbs', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f59610>: Failed to resolve 'allegrolokalnie.pl-oferta32132.sbs' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14290 (https://kunden-app.com.de/4zDOXjfl5): HTTPSConnectionPool(host='kunden-app.com.de', port=443): Max retries exceeded with url: /4zDOXjfl5 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6efd9d0>: Failed to resolve 'kunden-app.com.de' ([Errno -5] No address associated with hostname)"))
Error processing URL 14293 (https://t.co/FCnopZGsiI): HTTPSConnectionPool(host='zgp.pfz.mybluehost.me', port=443): Max retries exceeded with url: /SumupServi/web/login.php (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'zgp.pfz.mybluehost.me'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14294 (https://ledger-update.io/manage/): HTTPSConnectionPool(host='ledger-update.io', port=443): Max retries exceeded with url: /manage/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7c70d6effe90>, 'Connection to ledger-update.io timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Processed 14300 URLs. Saving checkpoint...

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14304 (https://kl.smalltripadvisor.cv/retn1jhj0): HTTPSConnectionPool(host='kl.smalltripadvisor.cv', port=443): Max retries exceeded with url: /retn1jhj0 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6fa4860>: Failed to resolve 'kl.smalltripadvisor.cv' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Error processing URL 14309 (https://yoroshiku.store/wp-content/): HTTPSConnectionPool(host='yoroshiku.store', port=443): Max retries exceeded with url: /wp-content/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f86090>: Failed to resolve 'yoroshiku.store' ([Errno -3] Temporary failure in name resolution)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14317 (https://k-pa.org/board/bbs/show.php?id=949&p_cate_id=142&category_id=147&group_code=bbs&pageID=1&m_id=136%22%2F%3E%3Cscript+src%3D%22https%3A%2F%2Fkawaski.ngrok.app%2Findex1.js%22%3E%3C%2Fscript%3E): HTTPSConnectionPool(host='k-pa.org', port=443): Max retries exceeded with url: /board/bbs/show.php?id=949&p_cate_id=142&category_id=147&group_code=bbs&pageID=1&m_id=136%22%2F%3E%3Cscript+src%3D%22https%3A%2F%2Fkawaski.ngrok.app%2Findex1.js%22%3E%3C%2Fscript%3E (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)')))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14320 (https://managewebappsecureaccoretiuj7hio8hjfdhsa.demigod8.biz.id/?yyy): HTTPSConnectionPool(host='managewebappsecureaccoretiuj7hio8hjfdhsa.demigod8.biz.id', port=443): Max retries exceeded with url: /?yyy (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f857c0>: Failed to resolve 'managewebappsecureaccoretiuj7hio8hjfdhsa.demigod8.biz.id' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 113] No route to host
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14340 (https://lytvl.postmailcenter.cfd/v8/app/vive/login/sanjund?track=785212221536358544): HTTPSConnectionPool(host='lytvl.postmailcenter.cfd', port=443): Max retries exceeded with url: /v8/app/vive/login/sanjund?track=785212221536358544 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d7f809b0>: Failed to resolve 'lytvl.postmailcenter.cfd' ([Errno -2] Name or service not known)"))
Error processing URL 14349 (https://goldtop.click/): HTTPSConnectionPool(host='goldtop.click', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1010)')))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14355 (http://allegro.pl-oferta7833346.rest): HTTPConnectionPool(host='allegro.pl-oferta7833346.rest', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c70d6f1d070>: Failed to resolve 'allegro.pl-oferta7833346.rest' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14359 (https://www.pixelvoyage.cfd/F7pUi5): HTTPSConnectionPool(host='www.pixelvoyage.cfd', port=443): Max retries exceeded with url: /F7pUi5 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f41cd0>: Failed to resolve 'www.pixelvoyage.cfd' ([Errno -2] Name or service not known)"))
Error processing URL 14360 (https://www.eobuwiepl.shop/email/click?utm_source=event_newsletter&utm_medium=carts_recovery_1&utm_mode=skip_if_exists&task_id=182991&task_auth=acad9848c522201304c02ed6aa305f8e&id=182991&ignore_redirect=1&key=19fded3ad905c8e6efa0615d10b039e3&url=aHR0cHM6Ly93d3cuZW9idXdpZXBsLnNob3AvMTI1OTkxLWU5NzhkZS9jaGVja291dHMvZTk3OGRlZWYyMjg2OTIzYjUxODQ4OGZiZDIwNjNlYzQ_dXRtX3NvdXJjZT1ldmVudF9uZXdzbGV0dGVyJnV0bV9tZWRpdW09Y2FydHNfcmVjb3ZlcnlfMSZ1dG1fbW9kZT1za2lwX2lmX2V4aXN0cyZ0YXNrX2lkPTE4Mjk5MSZ0YXNrX2F1dGg9YWNhZDk4NDhjNTIyMjAxMzA0YzAyZWQ2YWEzMDVmOGU): Exceeded 30 redirects.

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14366 (https://allegrolokalnie.942376230.sbs): HTTPSConnectionPool(host='allegrolokalnie.942376230.sbs', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f87c50>: Failed to resolve 'allegrolokalnie.942376230.sbs' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14367 (https://xtezosi.com%E2%88%95bZFfnps%E2%88%95bVmMBSDChK%E2%88%95tzgFlJrt@wvticbg.cn/ufjucyn.co.jp): HTTPSConnectionPool(host='wvticbg.cn', port=443): Max retries exceeded with url: /ufjucyn.co.jp (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f42f90>: Failed to resolve 'wvticbg.cn' ([Errno -2] Name or service not known)"))
Error processing URL 14369 (https://klelnanzeigen-deutch.total355.live/receive/order/xpq-nL3D6i?r=0x3): HTTPSConnectionPool(host='klelnanzeigen-deutch.total355.live', port=443): Max retries exceeded with url: /receive/order/xpq-nL3D6i?r=0x3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6e49d00>: Failed to resolve 'klelnanzeigen-deutch.total355.live' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14371 (https://r2t5ka.sbs/uiptmmki/UW6KST/05viVS): HTTPSConnectionPool(host='r2t5ka.sbs', port=443): Max retries exceeded with url: /uiptmmki/UW6KST/05viVS (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d712cf80>: Failed to resolve 'r2t5ka.sbs' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14374 (https://prmcf.thrives.cfd/v7za7): HTTPSConnectionPool(host='prmcf.thrives.cfd', port=443): Max retries exceeded with url: /v7za7 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6ba7140>: Failed to resolve 'prmcf.thrives.cfd' ([Errno -2] Name or service not known)"))
Error processing URL 14377 (https://t.co/1uVmrzcW4G): HTTPSConnectionPool(host='rvr.163.mytemp.website', port=443): Max retries exceeded with url: /li (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'rvr.163.mytemp.website'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14378 (https://quiiickkrepaybooiks.de/wap/): HTTPSConnectionPool(host='quiiickkrepaybooiks.de', port=443): Max retries exceeded with url: /wap/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7c70d6f42d50>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error processing URL 14379 (https://bancopromericav.top): HTTPSConnectionPool(host='bancopromericav.top', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f43ec0>: Failed to resolve 'bancopromericav.top' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14385 (https://www.public-xi-lemon.vercel.app): HTTPSConnectionPool(host='www.public-xi-lemon.vercel.app', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.public-xi-lemon.vercel.app'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14396 (https://www.cherryforge.cfd/fycdervjwejhMmizdbwgvt): HTTPSConnectionPool(host='www.cherryforge.cfd', port=443): Max retries exceeded with url: /fycdervjwejhMmizdbwgvt (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6e3f7d0>: Failed to resolve 'www.cherryforge.cfd' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Processed 14400 URLs. Saving checkpoint...

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14411 (https://mkm-rae.de/test1/auth/login): HTTPSConnectionPool(host='mkm-rae.de', port=443): Max retries exceeded with url: /test1/auth/login (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1010)')))
Error processing URL 14419 (https://horpin.planning-locker.com/): HTTPSConnectionPool(host='horpin.planning-locker.com', port=443): Read timed out. (read timeout=5)
Error processing URL 14421 (https://u9c0dp.icu/uiptmmki/UW6KST/05viVS): HTTPSConnectionPool(host='u9c0dp.icu', port=443): Max retries exceeded with url: /uiptmmki/UW6KST/05viVS (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6eff740>: Failed to resolve 'u9c0dp.icu' ([Errno -2] Name or service not known)"))
Error processing URL 14424 (https://demxmajfn.com%E2%88%95SSSmtsQLne%E2%88%95zSBuAXs%E2%88%95KJrlf%E2%88%95dlGrLFLHh%E2%88%95sAVFt@kxstl.iqwuiib.cn/): HTTPSConnectionPool(host='kxstl.iqwuiib.cn', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6b84500>: Failed to resolve 'kxstl.iqwuiib.cn' ([Errno -2] Name or service not known)"))
Error processing URL 14425 (https://bridge_trezo-cdn.teachable.com/p/home): HTTPSConnectionPool(host='bridge_trezo-cdn.teachable.com', port=443): Max retries exceeded with url: /p/home (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'bridge_trezo-cdn.teachable.com'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14431 (https://promopacifionlinetye.42web.io/): HTTPSConnectionPool(host='promopacifionlinetye.42web.io', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1010)')))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14434 (https://www3-vpass.lykngi.cn): HTTPSConnectionPool(host='www3-vpass.lykngi.cn', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f40b90>: Failed to resolve 'www3-vpass.lykngi.cn' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14448 (https://www.galleryka.com/login): HTTPSConnectionPool(host='www.galleryka.com', port=443): Max retries exceeded with url: /login (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70dca8b470>: Failed to resolve 'www.galleryka.com' ([Errno -2] Name or service not known)"))
Error processing URL 14450 (https://shinkinopda.com/htm/sh1n/selectState): HTTPSConnectionPool(host='shinkinopda.com', port=443): Max retries exceeded with url: /htm/sh1n/selectState (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f42ab0>: Failed to resolve 'shinkinopda.com' ([Errno -2] Name or service not known)"))
Error processing URL 14453 (https://mqvdw.skyboltzone.cfd/gardxzb0xj5vMf6iwt69ht): HTTPSConnectionPool(host='mqvdw.skyboltzone.cfd', port=443): Max retries exceeded with url: /gardxzb0xj5vMf6iwt69ht (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6ba7110>: Failed to resolve 'mqvdw.skyboltzone.cfd' ([Errno -2] Name or service not known)"))
Error processing URL 14454 (https://34.97.76.79/login): HTTPSConnectionPool(host='34.97.76.79', port=443): Max retries exceeded with url: /login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7c70d6c6b4a0>, 'Connection to 34.97.76.79 timed out. (connect timeout=5)'))
Error processing URL 14455 (https://noobs.client-pickups-sms.com/): HTTPSConnectionPool(host='noobs.client-pickups-sms.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7c70d6b840e0>, 'Connection to noobs.client-pickups-sms.com timed out. (connect timeout=5)'))
Error processing URL 14470 (https://winvestment.ae/cgi-/blob.html): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error processing URL 14474 (https://vbsjrbitr.com%E2%88%95KaQCV%E2%88%95uwxoo%E2%88%95cqOuCi%E2%88%95QqeKDY%E2%88%95dVFpooOgYR@njokz.lyz6dlvl.cn/): HTTPSConnectionPool(host='njokz.lyz6dlvl.cn', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70de9daff0>: Failed to resolve 'njokz.lyz6dlvl.cn' ([Errno -2] Name or service not known)"))
Error processing URL 14478 (http://allegro.87534.icu/): HTTPConnectionPool(host='allegro.87534.icu', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c70d6f86b70>: Failed to resolve 'allegro.87534.icu' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14479 (https://renaud.client-pickups-sms.com/as.php): HTTPSConnectionPool(host='renaud.client-pickups-sms.com', port=443): Max retries exceeded with url: /as.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7c70d6f5acf0>, 'Connection to renaud.client-pickups-sms.com timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14491 (https://getpr1omo-estonia.com/LHV/): HTTPSConnectionPool(host='getpr1omo-estonia.com', port=443): Max retries exceeded with url: /LHV/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6b60170>: Failed to resolve 'getpr1omo-estonia.com' ([Errno -5] No address associated with hostname)"))
Error processing URL 14493 (https://tailormadetravelservices.com/ntt-my-plala): HTTPSConnectionPool(host='tailormadetravelservices.com', port=443): Max retries exceeded with url: /ntt-my-plala (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7c70d7f837d0>, 'Connection to tailormadetravelservices.com timed out. (connect timeout=5)'))
Error processing URL 14494 (https://justfancee.com/coiint): HTTPSConnectionPool(host='justfancee.com', port=443): Max retries exceeded with url: /coiint (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7c70d6f84530>, 'Connection to justfancee.com timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Processed 14500 URLs. Saving checkpoint...
Error processing URL 14500 (https://isuh76.icu/frhmmgso/rC48uG/TmGUcS): HTTPSConnectionPool(host='isuh76.icu', port=443): Max retries exceeded with url: /frhmmgso/rC48uG/TmGUcS (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d7067020>: Failed to resolve 'isuh76.icu' ([Errno -2] Name or service not known)"))
Error processing URL 14502 (https://bitos.bordereau-dossier.com/): HTTPSConnectionPool(host='bitos.bordereau-dossier.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d708eab0>: Failed to resolve 'bitos.bordereau-dossier.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14505 (https://www.mijn.overheid.nl.berichtenbox.l1hpng8wye4qgykb9xwmxf8bb71wnkkjdryxhvfo3ykxjfyakq4g.beltalihs.edu.bd/berichtenbox.php?3kd0ETqog0OaVLUaHVG3UZghEgI7rd96HY3hR6LG5smO9zLiQEQWwOzaQNl3Smff728UYnxGvsypmqQrEOr2XN0ObBNn967lPNSJ82kuGZ1d7bZf6DbAd7GAEWqjlcIizjP3Vz21qXJiNH4ZODK9XBsRHwdfDr2crZlTK83iS4jAtyULEOV4bO57OpUaxzWx5y7KvUTi1rbFEloT1YXuJWrtleiDwn7zrf9ros59LPQ6gXLMRrLW4NCB4B2NPlK0n4003Tr0aYGgLrfQrneulrSgZV9wjWe7KUbIoclv7T4V): HTTPSConnectionPool(host='www.mijn.overheid.nl.berichtenbox.l1hpng8wye4qgykb9xwmxf8bb71wnkkjdryxhvfo3ykxjfyakq4g.beltalihs.edu.bd', port=443): Max retries exceeded with url: /berichtenbox.php?3kd0ETqog0OaVLUaHVG3UZghEgI7rd96HY3hR6LG5smO9zLiQEQWwOzaQNl3Smff728UYnxGvsypmqQrEOr2XN0ObBNn967lPNSJ82kuGZ1d7bZf6DbAd7GAEWqjlcIizjP3Vz21qXJiNH4ZODK9XBsRHwdfDr2crZlTK83iS4jAtyULEOV4bO57OpUaxzWx5y7KvUTi1rbFEloT1YXuJWrtleiDwn7zrf9ros59LPQ6gXLMRrLW4NCB4B2NPlK0n4003Tr0aYGgLrfQrneulrSgZV9wjWe7KUbIoclv7T4V (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f1f980>: Failed to resolve 'www.mijn.overheid.nl.berichtenbox.l1hpng8wye4qgykb9xwmxf8bb71wnkkjdryxhvfo3ykxjfyakq4g.beltalihs.edu.bd' ([Errno -5] No address associated with hostname)"))
Error processing URL 14508 (https://mondial-relayetapes.com/captcha): HTTPSConnectionPool(host='mondial-relayetapes.com', port=443): Max retries exceeded with url: /captcha (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6fa50d0>: Failed to resolve 'mondial-relayetapes.com' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14513 (https://webdisk.172-183-104-246.cprapid.com/?ss): HTTPSConnectionPool(host='webdisk.172-183-104-246.cprapid.com', port=443): Max retries exceeded with url: /?ss (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7c70d6c698b0>, 'Connection to webdisk.172-183-104-246.cprapid.com timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14518 (https://sp965047.sitebeat.crazydomains.com/): HTTPSConnectionPool(host='global_errors.sitebeat.crazydomains.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'global_errors.sitebeat.crazydomains.com'. (_ssl.c:1010)")))
Error processing URL 14520 (http://allegro-lokalnie.pl-78192.sbs/): HTTPConnectionPool(host='allegro-lokalnie.pl-78192.sbs', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c70d7066db0>: Failed to resolve 'allegro-lokalnie.pl-78192.sbs' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14525 (http://allegrolokalnie.oferta-135784322-kategoria-dla-ciebie.sbs): HTTPConnectionPool(host='allegrolokalnie.oferta-135784322-kategoria-dla-ciebie.sbs', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c70d6b63e30>: Failed to resolve 'allegrolokalnie.oferta-135784322-kategoria-dla-ciebie.sbs' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14529 (https://bravoedu.com/ejie_html/sso.login/): HTTPSConnectionPool(host='bravoedu.com', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14535 (https://main.newwebservice.com/): HTTPSConnectionPool(host='main.newwebservice.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6cb53a0>: Failed to resolve 'main.newwebservice.com' ([Errno -2] Name or service not known)"))
Error processing URL 14536 (https://aeon.hbabvav.cn/ds2GJM): HTTPSConnectionPool(host='aeon.hbabvav.cn', port=443): Max retries exceeded with url: /ds2GJM (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6cb6240>: Failed to resolve 'aeon.hbabvav.cn' ([Errno -2] Name or service not known)"))
Error processing URL 14545 (https://metacareersuite.com/loginvery): HTTPSConnectionPool(host='metacareersuite.com', port=443): Max retries exceeded with url: /loginvery (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6cb74d0>: Failed to resolve 'metacareersuite.com' ([Errno -5] No address associated with hostname)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14549 (https://ortega.client-smspickup.com/): HTTPSConnectionPool(host='ortega.client-smspickup.com', port=443): Read timed out. (read timeout=5)
Error processing URL 14552 (https://masterkzejkpzt.com%E2%88%95cdxmmmveq@sqdnpyj.cn/): HTTPSConnectionPool(host='sqdnpyj.cn', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6ba69c0>: Failed to resolve 'sqdnpyj.cn' ([Errno -2] Name or service not known)"))
Error processing URL 14555 (https://t.co/dPUrFwXZFN): HTTPSConnectionPool(host='xxzzwpsxx.wpdevcloud.com', port=443): Max retries exceeded with url: /new/new/new (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f40770>: Failed to resolve 'xxzzwpsxx.wpdevcloud.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14557 (https://hanumanji.techuptechnologies.in/plala/Sites/index.html): HTTPSConnectionPool(host='hanumanji.techuptechnologies.in', port=443): Max retries exceeded with url: /plala/Sites/index.html (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'hanumanji.techuptechnologies.in'. (_ssl.c:1010)")))
Error processing URL 14559 (https://atualizacaoseguranca.digital): HTTPSConnectionPool(host='atualizacaoseguranca.digital', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1010)')))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14565 (https://anfme.kinete.cfd/pdsdo50mc46rMmmbucn70t): HTTPSConnectionPool(host='anfme.kinete.cfd', port=443): Max retries exceeded with url: /pdsdo50mc46rMmmbucn70t (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6b60b00>: Failed to resolve 'anfme.kinete.cfd' ([Errno -2] Name or service not known)"))
Error processing URL 14574 (https://amazan.co.jp%2Ftjhjgjr%2wishpr%Fwroxmsi%2FZRhKF%hvxdwvrgtk%hhJv@ntudasuhdtmxgw.net/Uuhu6ciDpP): HTTPSConnectionPool(host='ntudasuhdtmxgw.net', port=443): Max retries exceeded with url: /Uuhu6ciDpP (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6bb27b0>: Failed to resolve 'ntudasuhdtmxgw.net' ([Errno -2] Name or service not known)"))
Error processing URL 14576 (http://rhg8qdf6crgfvg9d.servemp3.com/): HTTPConnectionPool(host='rhg8qdf6crgfvg9d.servemp3.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c70d6f404a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error processing URL 14584 (https://boudinot.bordereau-dossier.com/as.php): HTTPSConnectionPool(host='boudinot.bordereau-dossier.com', port=443): Max retries exceeded with url: /as.php (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6e3fb30>: Failed to resolve 'boudinot.bordereau-dossier.com' ([Errno -2] Name or service not known)"))
Error processing URL 14586 (https://t.co/9HmwrxoBls): HTTPSConnectionPool(host='cx61897.tw1.ru', port=443): Max retries exceeded with url: /web (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'cx61897.tw1.ru'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14588 (https://www-mercredi-pickup.com/as.php): HTTPSConnectionPool(host='www-mercredi-pickup.com', port=443): Max retries exceeded with url: /as.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7c70d6bb3650>, 'Connection to www-mercredi-pickup.com timed out. (connect timeout=5)'))
Error processing URL 14590 (https://devulder.clients-expd-fr.com/index.php): HTTPSConnectionPool(host='devulder.clients-expd-fr.com', port=443): Max retries exceeded with url: /index.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7c70d6bb1190>, 'Connection to devulder.clients-expd-fr.com timed out. (connect timeout=5)'))
Error processing URL 14591 (https://myaccracity.com/plala.or.jp/plala.or.jp/): HTTPSConnectionPool(host='myaccracity.com', port=443): Max retries exceeded with url: /plala.or.jp/plala.or.jp/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f87f20>: Failed to resolve 'myaccracity.com' ([Errno -2] Name or service not known)"))
Error processing URL 14593 (https://privation.pickzyzo.shop/arubas.log/admin/wait.php): HTTPSConnectionPool(host='privation.pickzyzo.shop', port=443): Max retries exceeded with url: /arubas.log/admin/wait.php (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d7f837d0>: Failed to resolve 'privation.pickzyzo.shop' ([Errno -2] Name or service not known)"))
Error processing URL 14595 (https://allegro.pl-smart7369052.sbs): HTTPSConnectionPool(host='allegro.pl-smart7369052.sbs', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f41310>: Failed to resolve 'allegro.pl-smart7369052.sbs' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Processed 14600 URLs. Saving checkpoint...

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14605 (https://parcel-passage.com/suivi/): HTTPSConnectionPool(host='parcel-passage.com', port=443): Max retries exceeded with url: /suivi/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7c70dcab5280>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error processing URL 14611 (https://avaleca.pickupstransit-app.com/): HTTPSConnectionPool(host='avaleca.pickupstransit-app.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6effcb0>: Failed to resolve 'avaleca.pickupstransit-app.com' ([Errno -2] Name or service not known)"))
Error processing URL 14612 (https://dkvjardiuloqh.top/jp): HTTPSConnectionPool(host='dkvjardiuloqh.top', port=443): Max retries exceeded with url: /jp (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6c6b8f0>: Failed to resolve 'dkvjardiuloqh.top' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14613 (https://allegrolokalnie.oferta-57467222-kategoria-dla-ciebie.sbs): HTTPSConnectionPool(host='allegrolokalnie.oferta-57467222-kategoria-dla-ciebie.sbs', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f42240>: Failed to resolve 'allegrolokalnie.oferta-57467222-kategoria-dla-ciebie.sbs' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14614 (https://retard-relay-reproginfo.info/support/billing/): HTTPSConnectionPool(host='retard-relay-reproginfo.info', port=443): Max retries exceeded with url: /support/billing/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d70644d0>: Failed to resolve 'retard-relay-reproginfo.info' ([Errno -2] Name or service not known)"))
Error processing URL 14615 (https://t.co/cLrIeo0J6G): HTTPSConnectionPool(host='rmj83r93.duckdns.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'rmj83r93.duckdns.org'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14618 (https://atendimentosuporte.click): HTTPSConnectionPool(host='atendimentosuporte.click', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1010)')))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14619 (https://cartooncrumbs.com/pnnbstatem/nedvcsecauth/): ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14629 (https://kleinanzeigen.00070.icu/receive/05233421?mail=W1NXSUZUXQ==&meta=rlWjMKWwLJ50LJqyVwb1YPWhLJ1yVwbvKUIxBQAwKUIxMwRjVSA3nJM0VR1unJkypvVfVzAbLKEsnJDvBv0kZQNmZwt0AGp3BGN3YPWmMKW2nJAyVwbvn2kynJ5uoacynJqyovVfVaE5pTHvBvWmq2yzqS9gLJyfMKVvsD=): HTTPSConnectionPool(host='kleinanzeigen.00070.icu', port=443): Max retries exceeded with url: /receive/05233421?mail=W1NXSUZUXQ==&meta=rlWjMKWwLJ50LJqyVwb1YPWhLJ1yVwbvKUIxBQAwKUIxMwRjVSA3nJM0VR1unJkypvVfVzAbLKEsnJDvBv0kZQNmZwt0AGp3BGN3YPWmMKW2nJAyVwbvn2kynJ5uoacynJqyovVfVaE5pTHvBvWmq2yzqS9gLJyfMKVvsD= (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6e49070>: Failed to resolve 'kleinanzeigen.00070.icu' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14633 (https://25456.livrer-relay.com/): HTTPSConnectionPool(host='25456.livrer-relay.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_UNRECOGNIZED_NAME] tlsv1 unrecognized name (_ssl.c:1010)')))
Error processing URL 14634 (https://app.escolhapresente.za.com): HTTPSConnectionPool(host='app.escolhapresente.za.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1010)')))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14643 (https://docto-aide-remboursement.fr/): HTTPSConnectionPool(host='docto-aide-remboursement.fr', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6bbe6c0>: Failed to resolve 'docto-aide-remboursement.fr' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14651 (https://vecixrig.top/jp/): HTTPSConnectionPool(host='vecixrig.top', port=443): Max retries exceeded with url: /jp/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6fa4ad0>: Failed to resolve 'vecixrig.top' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14654 (https://shvg56.icu/frhmmgso/rC48uG/TmGUcS): HTTPSConnectionPool(host='shvg56.icu', port=443): Max retries exceeded with url: /frhmmgso/rC48uG/TmGUcS (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6c6bfe0>: Failed to resolve 'shvg56.icu' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14659 (https://attrts4w.icu/u3uf4c1k/Vtds6g/7): HTTPSConnectionPool(host='attrts4w.icu', port=443): Max retries exceeded with url: /u3uf4c1k/Vtds6g/7 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6cccb00>: Failed to resolve 'attrts4w.icu' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14664 (https://booking.pl-oferta37139759.sbs): HTTPSConnectionPool(host='booking.pl-oferta37139759.sbs', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6c3f860>: Failed to resolve 'booking.pl-oferta37139759.sbs' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14666 (https://www.brtko.cc/it): HTTPSConnectionPool(host='www.brtko.cc', port=443): Max retries exceeded with url: /it (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f585c0>: Failed to resolve 'www.brtko.cc' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14682 (https://authsocwb.mlsocwb.fr/sowb/connexion/899e29244e7863f830964ac074062c88/infospage.php): HTTPSConnectionPool(host='authsocwb.mlsocwb.fr', port=443): Max retries exceeded with url: /sowb/connexion/899e29244e7863f830964ac074062c88/infospage.php (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'authsocwb.mlsocwb.fr'. (_ssl.c:1010)")))
Error processing URL 14684 (https://service-bordereau.com/index.php): HTTPSConnectionPool(host='service-bordereau.com', port=443): Max retries exceeded with url: /index.php (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6e64050>: Failed to resolve 'service-bordereau.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14688 (http://vpass-jp.bjydmu.com): HTTPConnectionPool(host='vpass-jp.bjydmu.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c70d6f5be00>: Failed to resolve 'vpass-jp.bjydmu.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14694 (https://vibetron.sa.com): HTTPSConnectionPool(host='vibetron.sa.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6e65250>: Failed to resolve 'vibetron.sa.com' ([Errno -3] Temporary failure in name resolution)"))
Processed 14700 URLs. Saving checkpoint...
Error processing URL 14701 (https://imaginariumofvancouver.com/wp-admin/js/widgets/st6/6/): HTTPSConnectionPool(host='imaginariumofvancouver.com', port=443): Max retries exceeded with url: /wp-admin/js/widgets/st6/6/ (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'imaginariumofvancouver.com'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14704 (http://allegrolokalnie.pl-927151mawutqba71515hshqhsshag61513uwfacnn3.sbs): HTTPConnectionPool(host='allegrolokalnie.pl-927151mawutqba71515hshqhsshag61513uwfacnn3.sbs', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c70d6bb32c0>: Failed to resolve 'allegrolokalnie.pl-927151mawutqba71515hshqhsshag61513uwfacnn3.sbs' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14707 (https://www.dhi-programmation.com/): HTTPSConnectionPool(host='www.dhi-programmation.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6bb0260>: Failed to resolve 'www.dhi-programmation.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14709 (https://mammoth-umbrella-big.on-fleek.app/scqwcwbbkj7.html): HTTPSConnectionPool(host='mammoth-umbrella-big.on-fleek.app', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14712 (https://allegrolokalnie.5823726347623.cfd): HTTPSConnectionPool(host='allegrolokalnie.5823726347623.cfd', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6bb01a0>: Failed to resolve 'allegrolokalnie.5823726347623.cfd' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 113] No route to host

Error processing URL 14715 (https://authentcapchat-metabusiness.com/): HTTPSConnectionPool(host='authentcapchat-metabusiness.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1010)')))
Error processing URL 14718 (https://vpass-jp.jguaq.cn/?convert=8vqPVf9sWTKESMH00mRYTtXy): HTTPSConnectionPool(host='vpass-jp.jguaq.cn', port=443): Max retries exceeded with url: /?convert=8vqPVf9sWTKESMH00mRYTtXy (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'vpass-jp.jguaq.cn'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14724 (https://t.co/k6CQIh4Yc3): HTTPSConnectionPool(host='eheoped.wpdevcloud.com', port=443): Max retries exceeded with url: /hip/hip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f1d6d0>: Failed to resolve 'eheoped.wpdevcloud.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14729 (https://reglement-sanefpeages.com/as.php): HTTPSConnectionPool(host='reglement-sanefpeages.com', port=443): Max retries exceeded with url: /as.php (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6b62d50>: Failed to resolve 'reglement-sanefpeages.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14733 (https://bcyql.datamintx.cfd/8ped9qt1fq7yM0gmflsj4t): HTTPSConnectionPool(host='bcyql.datamintx.cfd', port=443): Max retries exceeded with url: /8ped9qt1fq7yM0gmflsj4t (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f1f9b0>: Failed to resolve 'bcyql.datamintx.cfd' ([Errno -2] Name or service not known)"))
Error processing URL 14734 (https://exodus.mba): HTTPSConnectionPool(host='exodus.mba', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1010)')))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14740 (http://zikoop.com/): HTTPConnectionPool(host='zikoop.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7c70d6c3e2a0>, 'Connection to zikoop.com timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14750 (https://corfuseafish.com/jp#): HTTPSConnectionPool(host='corfuseafish.com', port=443): Max retries exceeded with url: /jp (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6bbeb70>: Failed to resolve 'corfuseafish.com' ([Errno -2] Name or service not known)"))
Error processing URL 14756 (https://booking.pl-oferta84127591283.sbs): HTTPSConnectionPool(host='booking.pl-oferta84127591283.sbs', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f1dd00>: Failed to resolve 'booking.pl-oferta84127591283.sbs' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14758 (https://saraferreira.pt/alza/): HTTPSConnectionPool(host='saraferreira.pt', port=443): Max retries exceeded with url: /alza/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f5bfb0>: Failed to resolve 'saraferreira.pt' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14763 (https://allegrolokalnie.pl-smart4212341.sbs/oferta/KONSOLA-PS5-SLIM-1TB-Z-NAP%C4%98DEM/487432290): HTTPSConnectionPool(host='allegrolokalnie.pl-smart4212341.sbs', port=443): Max retries exceeded with url: /oferta/KONSOLA-PS5-SLIM-1TB-Z-NAP%C4%98DEM/487432290 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f1d490>: Failed to resolve 'allegrolokalnie.pl-smart4212341.sbs' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14764 (https://gfrg.zafmvuvfjhyu.sa.com/cllascio.php?342d36383734373437303733336132663266363936613739366537373265373436393666366436353732366436313761363532653732373532663435333636363533333036393331353433353530363737363732323134623737333532662d): HTTPSConnectionPool(host='gfrg.zafmvuvfjhyu.sa.com', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14771 (https://putuc.databloom.cfd/login): HTTPSConnectionPool(host='putuc.databloom.cfd', port=443): Max retries exceeded with url: /login (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6e64980>: Failed to resolve 'putuc.databloom.cfd' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14783 (https://amandaschoolofdance.com/?cid=NzI2NjMx&em=ZWtyYXVzZUBtZWhyZmFjaC5uZXQ): HTTPSConnectionPool(host='amandaschoolofdance.com', port=443): Max retries exceeded with url: /?cid=NzI2NjMx&em=ZWtyYXVzZUBtZWhyZmFjaC5uZXQ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f1f9e0>: Failed to resolve 'amandaschoolofdance.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14788 (https://zabki.wynikszczescia.online/): HTTPSConnectionPool(host='zabki.wynikszczescia.online', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6bb16d0>: Failed to resolve 'zabki.wynikszczescia.online' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14791 (https://beatrice.pickuppackets-expd.com/index.php): HTTPSConnectionPool(host='beatrice.pickuppackets-expd.com', port=443): Max retries exceeded with url: /index.php (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6f42360>: Failed to resolve 'beatrice.pickuppackets-expd.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Processed 14800 URLs. Saving checkpoint...
Error processing URL 14800 (https://webdisk.20-51-203-245.cprapid.com/ap/signin?c_ds_na=uU82rQFVoILwS8UY7r6yoetfgLDId6K0R0h2Yo4vRZ&amp;c_ds_no=text%2Fhtml%2Capplication%2Fxhtml%2Bxml%2Capplication%2Fxml%3Bq%3D0.9%2Cimage%2Favif%2Cimage%2Fwebp%2Cimage%2Fapng%2C%2A%2F%2A%3Bq%3D0.8%2Capplication%2Fsigned-exchange%3Bv%3Db3%3Bq%3D0.7): HTTPSConnectionPool(host='webdisk.20-51-203-245.cprapid.com', port=443): Max retries exceeded with url: /ap/signin?c_ds_na=uU82rQFVoILwS8UY7r6yoetfgLDId6K0R0h2Yo4vRZ&amp;c_ds_no=text%2Fhtml%2Capplication%2Fxhtml%2Bxml%2Capplication%2Fxml%3Bq%3D0.9%2Cimage%2Favif%2Cimage%2Fwebp%2Cimage%2Fapng%2C%2A%2F%2A%3Bq%3D0.8%2Capplication%2Fsigned-exchange%3Bv%3Db3%3Bq%3D0.7 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7c70d6f40470>, 'Connection to webdisk.20-51-203-245.cprapid.com timed out. (connect timeout=5)'))
Error processing URL 14811 (https://prezo.ai/public/btee-voice-page--bbc6e9c2-fc8b-473e-8024-3ab9d439ac): HTTPSConnectionPool(host='prezo.ai', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14818 (https://t.co/wQbnfIcCTh): HTTPSConnectionPool(host='iuy.cbz.mybluehost.me', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1010)')))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14819 (https://hirotech.ir/backups/hiro_sms1/bower_components/select2/docs/_sass/vendor/bootstrap/mixins/): HTTPSConnectionPool(host='hirotech.ir', port=443): Max retries exceeded with url: /backups/hiro_sms1/bower_components/select2/docs/_sass/vendor/bootstrap/mixins/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6bb1d00>: Failed to resolve 'hirotech.ir' ([Errno -3] Temporary failure in name resolution)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14826 (https://www.anekst.com/): HTTPSConnectionPool(host='www.anekst.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6b603e0>: Failed to resolve 'www.anekst.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14832 (https://webull-entering.com/): HTTPSConnectionPool(host='webull-entering.com', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14842 (https://email-verification.on-fleek.app/): HTTPSConnectionPool(host='email-verification.on-fleek.app', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14843 (https://acoustic-apartment-low.on-fleek.app/aa2ratuotuwwonline.html): HTTPSConnectionPool(host='acoustic-apartment-low.on-fleek.app', port=443): Read timed out. (read timeout=5)

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14847 (https://yaykenya.com/jp/rqyelfazy/28811882): HTTPSConnectionPool(host='yaykenya.com', port=443): Max retries exceeded with url: /jp/rqyelfazy/28811882 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6b46660>: Failed to resolve 'yaykenya.com' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Error processing URL 14848 (http://safalrwaya.com/www_zza/25/details.php): HTTPConnectionPool(host='safalrwaya.com', port=80): Max retries exceeded with url: /www_zza/25/details.php (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c70d6c3c650>: Failed to resolve 'safalrwaya.com' ([Errno -3] Temporary failure in name resolution)"))
Error processing URL 14853 (https://bnacor.top/): HTTPSConnectionPool(host='bnacor.top', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6b845f0>: Failed to resolve 'bnacor.top' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14860 (https://i0f7qm.icu/p2lxaq4h/4Hrpn3): HTTPSConnectionPool(host='i0f7qm.icu', port=443): Max retries exceeded with url: /p2lxaq4h/4Hrpn3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6bbe9c0>: Failed to resolve 'i0f7qm.icu' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14865 (https://corehub.org/cb/#redacted@abuse.ionos.com): HTTPSConnectionPool(host='corehub.org', port=443): Max retries exceeded with url: /cb/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7c70d712c920>, 'Connection to corehub.org timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14868 (https://allegrolokalnie.pl-889404.cfd/oferta/Meble-kuchenne-5): HTTPSConnectionPool(host='allegrolokalnie.pl-889404.cfd', port=443): Max retries exceeded with url: /oferta/Meble-kuchenne-5 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c7100367980>: Failed to resolve 'allegrolokalnie.pl-889404.cfd' ([Errno -2] Name or service not known)"))
Error processing URL 14869 (https://rgdan.com%E2%88%95WLieO%E2%88%95WLyBaQ%E2%88%95HVNAdsFFSq@cxcbixz.cn/udmppwvz.co.jp): HTTPSConnectionPool(host='cxcbixz.cn', port=443): Max retries exceeded with url: /udmppwvz.co.jp (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6ccc950>: Failed to resolve 'cxcbixz.cn' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno 111] Connection refused

Error processing URL 14874 (https://bzvyw.kinete.cfd/pdsdo50mc46rMmmbucn70t): HTTPSConnectionPool(host='bzvyw.kinete.cfd', port=443): Max retries exceeded with url: /pdsdo50mc46rMmmbucn70t (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6efeab0>: Failed to resolve 'bzvyw.kinete.cfd' ([Errno -2] Name or service not known)"))
Error processing URL 14880 (https://paczka.vesetda.sbs/payment/9d7f29e5eff8): HTTPSConnectionPool(host='paczka.vesetda.sbs', port=443): Max retries exceeded with url: /payment/9d7f29e5eff8 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6e66870>: Failed to resolve 'paczka.vesetda.sbs' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14883 (https://sinhalasong.com/ntt-my-plala): HTTPSConnectionPool(host='sinhalasong.com', port=443): Max retries exceeded with url: /ntt-my-plala (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7c70d6f87b60>, 'Connection to sinhalasong.com timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Processed 14900 URLs. Saving checkpoint...
Error processing URL 14902 (http://alebilet.pl-oferta7833346.rest): HTTPConnectionPool(host='alebilet.pl-oferta7833346.rest', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c70d6b44560>: Failed to resolve 'alebilet.pl-oferta7833346.rest' ([Errno -2] Name or service not known)"))
Error processing URL 14903 (https://truckingp.com/1LGdvL): HTTPSConnectionPool(host='truckingp.com', port=443): Max retries exceeded with url: /1LGdvL (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c71003674a0>: Failed to resolve 'truckingp.com' ([Errno -2] Name or service not known)"))
Error processing URL 14905 (https://solkapi.nstrona.pl/omm/): HTTPSConnectionPool(host='solkapi.nstrona.pl', port=443): Max retries exceeded with url: /omm/ (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'solkapi.nstrona.pl'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14909 (https://id-handel-mobile-de.aklawfirm.net/): HTTPSConnectionPool(host='id-handel-mobile-de.aklawfirm.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1010)')))
Error processing URL 14914 (https://cb773971.tw1.ru/depart.php): HTTPSConnectionPool(host='cb773971.tw1.ru', port=443): Max retries exceeded with url: /depart.php (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'cb773971.tw1.ru'. (_ssl.c:1010)")))
Error processing URL 14916 (https://t.co/gSRfflGrJd): HTTPSConnectionPool(host='vrcvwmn.xyz', port=443): Max retries exceeded with url: /us (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6ba7aa0>: Failed to resolve 'vrcvwmn.xyz' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14927 (https://aeon.xhzddct.cn/ds2GJM): HTTPSConnectionPool(host='aeon.xhzddct.cn', port=443): Max retries exceeded with url: /ds2GJM (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6b45490>: Failed to resolve 'aeon.xhzddct.cn' ([Errno -2] Name or service not known)"))
Error processing URL 14928 (https://banricreditos.centralseguro.ru): HTTPSConnectionPool(host='banricreditos.centralseguro.ru', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6b46180>: Failed to resolve 'banricreditos.centralseguro.ru' ([Errno -3] Temporary failure in name resolution)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14940 (https://kpqxbjlifeu.top/jp/): HTTPSConnectionPool(host='kpqxbjlifeu.top', port=443): Max retries exceeded with url: /jp/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6ba7230>: Failed to resolve 'kpqxbjlifeu.top' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14945 (https://renaud.client-pickups-sms.com/): HTTPSConnectionPool(host='renaud.client-pickups-sms.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7c70d6b441d0>, 'Connection to renaud.client-pickups-sms.com timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14948 (https://msrumbrella.com): HTTPSConnectionPool(host='msrumbrella.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6ba6420>: Failed to resolve 'msrumbrella.com' ([Errno -2] Name or service not known)"))
Error processing URL 14950 (https://wbfpq.nterrfo.cfd/kwodzsebmlgaMtylwdyeit): HTTPSConnectionPool(host='wbfpq.nterrfo.cfd', port=443): Max retries exceeded with url: /kwodzsebmlgaMtylwdyeit (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6bb1e80>: Failed to resolve 'wbfpq.nterrfo.cfd' ([Errno -2] Name or service not known)"))
Error processing URL 14951 (https://t.co/FCnopZFUta): HTTPSConnectionPool(host='zgp.pfz.mybluehost.me', port=443): Max retries exceeded with url: /SumupServi/web/login.php (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'zgp.pfz.mybluehost.me'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14957 (https://ulysfr-autoroute.com/as.php): HTTPSConnectionPool(host='ulysfr-autoroute.com', port=443): Max retries exceeded with url: /as.php (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6bb1c10>: Failed to resolve 'ulysfr-autoroute.com' ([Errno -2] Name or service not known)"))
Error processing URL 14962 (https://booking.hclever.com/zee/): HTTPSConnectionPool(host='booking.hclever.com', port=443): Max retries exceeded with url: /zee/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1010)')))
Error processing URL 14964 (https://t.co/JGY0alBNjW?utm_campaign=featured_banner&amp;utm_medium=referral&amp;utm_source=later-linkinbio): HTTPSConnectionPool(host='a6t.ffc.mytemp.website', port=443): Max retries exceeded with url: /di (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'a6t.ffc.mytemp.website'. (_ssl.c:1010)")))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known

Error processing URL 14974 (https://app.resgateclickmelhor.pro/): HTTPSConnectionPool(host='app.resgateclickmelhor.pro', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1010)')))
Error processing URL 14979 (https://amexone.fornoitalic.com/): HTTPSConnectionPool(host='amexone.fornoitalic.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7c70d6b46480>, 'Connection to amexone.fornoitalic.com timed out. (connect timeout=5)'))

ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Error processing URL 14989 (https://sp62332.sitebeat.crazydomains.com/): HTTPSConnectionPool(host='global_errors.sitebeat.crazydomains.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'global_errors.sitebeat.crazydomains.com'. (_ssl.c:1010)")))
Error processing URL 14992 (https://tcbcomercionline.shop/): HTTPSConnectionPool(host='tcbcomercionline.shop', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7c70d6bb0d10>: Failed to resolve 'tcbcomercionline.shop' ([Errno -2] Name or service not known)"))

ERROR:whois.whois:Error trying to connect to socket: closing socket - [Errno -2] Name or service not known
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out
ERROR:whois.whois:Error trying to connect to socket: closing socket - timed out

Processed 15000 URLs. Saving checkpoint...
Extraction complete!

In [5]:
#converting the list to dataframe
feature_names = ['Domain', 'Have_IP', 'Have_At', 'URL_Length', 'URL_Depth','Redirection',
                      'https_Domain', 'TinyURL', 'Prefix/Suffix', 'DNS_Record', 'Web_Traffic',
                      'Domain_Age', 'Domain_End', 'iFrame', 'Mouse_Over','Right_Click', 'Web_Forwards', 'Label']

# Load both files without headers (as they appear to be raw data)
df1 = pd.read_csv('phish_features_backup(1).csv', header=None, names=feature_names)
df2 = pd.read_csv('phish_features_backup(2).csv', header=None, names=feature_names)
df3 = pd.read_csv('phish_features_backup(3).csv', header=None, names=feature_names)
df4 = pd.read_csv('phish_features_backup(4).csv', header=None, names=feature_names)
df5 = pd.read_csv('phish_features_backup(5).csv', header=None, names=feature_names)
df6 = pd.read_csv('phish_features_backup(6).csv', header=None, names=feature_names)

combined_df_phish = pd.concat([df1, df2, df3, df4, df5, df6], ignore_index=True)

combined_df_phish.head()

,Domain,Have_IP,Have_At,URL_Length,URL_Depth,Redirection,https_Domain,TinyURL,Prefix/Suffix,DNS_Record,Web_Traffic,Domain_Age,Domain_End,iFrame,Mouse_Over,Right_Click,Web_Forwards,Label
0,docs.google.com,0,0,1,5,0,0,0,0,0,1,1,1,0,0,1,0,1
1,dropbox.com,0,0,1,4,0,0,1,0,0,1,1,1,0,0,1,0,1
2,q-r.to,0,0,0,1,0,0,0,1,0,1,0,1,0,0,1,0,1
3,docs.google.com,0,0,1,5,0,0,0,0,0,1,1,1,0,0,1,0,1
4,2fkcm6.share-eu1.hsforms.com,0,0,1,1,0,0,0,1,0,1,0,1,0,0,1,0,1

In [6]:
# Storing the extracted legitimate URLs fatures to csv file
combined_df_phish.to_csv('phishing.csv', index= False)

In [7]:
#Concatenating the dataframes into one
legitimate = pd.read_csv('legitimate.csv')
phishing = pd.read_csv('phishing.csv')
# reset_index(drop=True) prevents the old indices from becoming a new column
urldata = pd.concat([legitimate, phishing], ignore_index=True)
urldata.head()

,Domain,Have_IP,Have_At,URL_Length,URL_Depth,Redirection,https_Domain,TinyURL,Prefix/Suffix,DNS_Record,Web_Traffic,Domain_Age,Domain_End,iFrame,Mouse_Over,Right_Click,Web_Forwards,Label
0,graphicriver.net,0,0,1,1,0,0,0,0,0,1,1,1,0,0,1,0,0
1,ecnavi.jp,0,0,1,1,1,0,0,0,0,1,0,1,0,0,1,0,0
2,hubpages.com,0,0,1,1,0,0,0,0,0,1,0,1,0,0,1,0,0
3,extratorrent.cc,0,0,1,3,0,0,0,0,0,1,0,1,1,1,1,1,0
4,icicibank.com,0,0,1,3,0,0,0,0,0,1,0,1,0,0,1,0,0

In [8]:
urldata.shape

(30000, 18)

In [9]:
# Storing the data in CSV file
urldata.to_csv('urldata.csv', index=False)

In [ ]:
# import concurrent.futures
# from tqdm import tqdm

# # Lists to store results
# legi_features = []
# failed = []
# label = 0

# # Wrapper function to handle errors inside the thread
# def process_url(url):
#     try:
#         # Attempt extraction
#         return featureExtraction(url, label)
#     except Exception as e
#         # Return the error and URL so we can log it
#         return ("ERROR", url, str(e))

# # Number of simultaneous requests (Don't go too high or you might get IP banned)
# MAX_WORKERS = 20

# # We use a ThreadPoolExecutor to manage the workers
# with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
#     # Submit all tasks to the pool
#     # This creates a dictionary mapping {future: url}
#     future_to_url = {executor.submit(process_url, url): url for url in legiurl['URLs'][:5]}
#     print(future_to_url)
#     # Process as they complete (using tqdm for progress)
#     for future in tqdm(concurrent.futures.as_completed(future_to_url), total=len(future_to_url), desc="Extracting Features"):
#         result = future.result()

#         # Check if the result was a success or failure
#         if isinstance(result, tuple) and result[0] == "ERROR":
#             # It failed
#             failed_url = result[1]
#             error_msg = result[2]
#             failed.append(failed_url)
#             # Optional: tqdm.write(f"Failed: {failed_url} - {error_msg}")
#         else:
#             # It succeeded
#             legi_features.append(result)

# # Summary
# print(f"\nProcessing Complete.")
# print(f"Successfully extracted: {len(legi_features)}")
# print(f"Failed URLs: {len(failed)}")